### ISSUE TITLE
Intermittent RATS failure on BOSH lite environments

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/routing-release#100]
## Issue

The release integration team sees that `Tcp Routing / multiple-app ports / single external port with multiple app ports / should switch between ports ` fails in roughly 1 in 10 runs on our BOSH lite environments, with a "connection reset by peer" error.

This issue does not occur on our full BOSH GCP environments. We've yet to conduct a more in-depth exploration.

## `RATS Failure` Output Results
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/lite-rats/builds/362
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/lite-rats/builds/351
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/lite-rats/builds/335
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/lite-rats/builds/328
https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/lite-rats/builds/315

**Comment by aaronshurley** [comment]
@njbennett Thank you for filing this issue. We haven't seen this issue in our CI environments but we aren't running the same setup, we are running RATS on full BOSHs with cf-deployment and on BOSH lites with cf-release.

We'll keep this issue up so we don't lose track of this but I'll leave it to the PM's to prioritize for further investigation.

**Comment by shalako** [comment]
cf-release will be deprecated in a week, at which point we should tear down our deployments and replace them with cf-deployment on BOSH-lite.

**Comment by zachgersh** [comment]
@njbennett - can I also ask what cf-deployment / bosh-lite versions you were using?

**Comment by charleshansen** [comment]
@njbennett The error you are seeing looks like a connection reset between the process running RATS and the load balancer or the tcp-router. This could be an indication of flaky networking in your particular environment.

That said, we did just update RATS to be more resilient to this type of error e4a8a3779e3dbc4b1de6ac7a823b8fd1730389ee

If you want, you can try this newest code. I'm not sure exactly when we will cut a new release and it will be bumped to master.

**Comment by aaronshurley** [comment]
This was completed some time ago, closing out the issue
