### ISSUE TITLE
Issue while using routing release version 0.168.0

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/routing-release#101]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Facing issue w.r.t. routing release version, not able to access the app, getting "connection refused error"
while connecting.

Using cf release version to be 283.

Thanks in advance.

**Comment by rosenhouse** [comment]
@lordcf Thanks for the report.  Could you provide more details?  Things that would be helpful for debugging:
- whether you're making an HTTP request to Gorouter, or a TCP connection to TCP Router, or something else
   - if http, the HTTP status code you're seeing in response
- where you're seeing that "connection refused error" (on the client side?  in some log line in a system component?)
- what kind of infrastructure you're running on (GCP, VSphere, AWS, OpenStack, BOSH-lite, something else?)
- what kind of load balancer, if any, you have between your client and your CF
- if you have SSL/TLS configured on one or more hops of the connection (e.g. between load balancer and router)
- any log lines in the router, or on your load balancer that you can correlate with the error you've reported.

Also, please note that [CF Release is officially end-of-life](https://lists.cloudfoundry.org/g/cf-dev/message/7760).  We recommend you upgrade to [CF Deployment](https://github.com/cloudfoundry/cf-deployment).

**Comment by lordcf** [comment]
Hello team,
We are facing issue while upgrading cf release from v281 to v283 with routing release v146.
We are using tcp connection to access our applications through tcp router. 
Intitially we deployed cf v281 with routing release v146.It was working fine.Then we upgraded cf  from v281 to v283.
We were able to see router groups.But when we push the app using tcp route,we are getting error "The router group could not be found".

We access the tcp application using "curl tcp.example.com:Por t-name" 
We are using cf-release since we are still working on investigation to migrate our production environments to work with cf-deployments
We are running cf on AWS and using AWS ELB for load balancing.

**Comment by shalako** [comment]
Around this time we deprecated support for etcd as a backing store for routing-api. Have you followed the instructions on the README for that version, for migrating from etcd to a relational database?

Be sure to look at the branch of the README for your version. We removed these docs from master when we dripped support for etcd.

**Comment by shubhaat** [comment]
@lordcf - closing this. If the suggestion above to migrate from etcd to a relational database does not resolve the issue, feel free to reopen.
