### ISSUE TITLE
How to use another port rather than 443 when the ssl is enabled for router?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/routing-release#102]
In current router release, when the ssl is enabled, the port is 443 by default. But I want to use another port and did not found how to configure it.

**Comment by aaronshurley** [comment]
Hi @qibobo,

Currently, the HTTPS port is not configurable. Could you please let us know your use case for wanting to change this?

**Comment by qibobo** [comment]
@aaronshurley  We have two bosh-lites deployed on a physical machine, and two concourse pipelines deploy cf and our own applications to the bosh-lites. So we do some iptable mapping on the physical machine. The tcp request to port 443 of the physical machine will be forwarded to the first bosh-lite as  the router's ssl port is 443 by default. While 443 is occupied by the first bosh-lite, we want make the router's port of the second bosh-lite another port rather than 443.

**Comment by shubhaat** [comment]
Hi @qibobo ,

@aaronshurley - could we accept a PR for this, and if so can we give some pointers to @qibobo for it. 

@qibobo - if you do make a PR we would prefer the property is also exposed through the job spec  as `router.tls_port`.

**Comment by qibobo** [comment]
@aaronshurley @shubhaat  I'd like to provide a PR for it.

**Comment by zachgersh** [comment]
@qibobo - please go for it and ping us.
