### ISSUE TITLE
HTTP apps not getting pushed on cf once tcp is down.

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/routing-release#103]
Hi team,

We were facing issue while pushing http apps on cf when tcp was down.
First we were using cf v281 and tcp-routing v146.We simply configured routing_api set to 'true' in cf manifest to enable routing while pushing tcp apps.
Because of some reason,tcp-routing went down,so we were not able to push tcp apps on cf.
Also we were facing error while pushing http apps on cf.

As suggested by community  ,we upgraded cf v to v283 and tcp_routing to v163.
Now suppose if because of some reason tcp is not available or down,then does there exist some way so that we can push http apps individually on cf without tcp .?

Thanks,

**Comment by shubhaat** [comment]
This is a known issue.

If you have created a shared domain that is associated with a router-group, as you would to enable app developers to create TCP routes, and the Routing API subsequently become unavailable, then many CLI commands will fail, as Cloud Controller calls out to Routing API to determine the port range and/or type of the associated router group.

We recommend either keeping Routing API available (it is designed to be HA), or disabling support for TCP Routing by removing the shared domain associated with a router group.

**Comment by aaronshurley** [comment]
@lordcf Is there anything further you'd like to discuss about this issue?

**Comment by aaronshurley** [comment]
@lordcf just checking if there's anything else, otherwise we'll close out this issue

**Comment by KauzClay** [comment]
@lordcf We are closing this issue. Feel free to reopen, or open another issue, if you are still having issues.
