### ISSUE TITLE
TCP v164 issue

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/routing-release#104]
We have upgraded tcp-routing from v 0.146.0 to v 0.163.0 with cf v 283, without any issues.
But on upgrading tcp-routing from v 0.163.0 to  v 0.164.0, facing an issue to curl the apps.
We are getting error as "connection refused" with cf v 283.
Have commented out "tcp_emitter" jobs, just kept the oauth_secret property for tcp_emitter inside routing manifest.
We also checked the logs inside tcp_router, found an error as "tcp-router.watcher.failed-to-get-next-routing-api-event".
Can someone please suggest some solution for it ??

**Comment by lordcf** [comment]
We are using We are aware that cf release v283 and routing release v163.When we upgrade routing from v163 to v164,we are getting error "empty reply from server" .

While upgrading  routing release from v163 to v164,we have  commented out "tcp_emitter" jobs, just kept the oauth_secret property for tcp_emitter inside routing manifest.

And as mentioned in link "https://lists.cloudfoundry.org/g/cf-dev/attachment/7102/0/attachment.html",
 also added following properties in cf manifest file .
               tcp.enabled: true
               routing_api.url: defaults toÂ http://routing-api.service.cf.internal
               routing_api.port: defaults to 3000
               routing_api.auth_enabled: defaults to true

We also checked the logs inside tcp_router, found an error as "tcp-router.watcher.failed-to-get-next-routing-api-event".
Also set the log_level to debug for routing_api and tcp_router.

@shalako @rosenhouse @shubhaat @Nino-K 
We are aware that cf release is no longer supported by community but we are using cf release in production environment.Migration to cf deployment is under progress.But before that we need to upgrade routing from v163 to v168.Can Someone please help us out?

**Comment by shalako** [comment]
Hi there. Please stop by our Slack channel - cloudfoundry `#routing` and ping the interrupt pair. Someone should be able to chat with you about it.

**Comment by aaronshurley** [comment]
@lordcf is this the same issue as https://github.com/cloudfoundry/routing-release/issues/113?

If so, could we please close one of them?

**Comment by lordcf** [comment]
Yes, this ticket could be closed.
