### ISSUE TITLE
gorouter job never deletes its PID file

### ISSUE THREAD

**Issue by giner** [cloudfoundry/routing-release#109]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

gorouter job doesn't delete its PID file during deploy which **sometimes** leads to the situation when gorouter doesn't start but the deploy continues because another process starts with the same PID

## Context

Deploying >30 router VMs with "bosh deploy"

## Steps to Reproduce

run `bosh stop router/N` and check `cat /var/vcap/sys/run/gorouter/gorouter.pid` after it is stopped

## Expected result

pid file should be deleted

## Current result

pid file is not deleted

## Possible Fix

This happens because monit (when configured with pidfile) checks if process with the pid exists before executing "stop program" and doesn't execute `gorouter_ctl stop` if pid doesn't exist. At the same time the process with that PID cannot exist at that moment because the drain script ensures that it doesn't.

To fix this either pid file should be removed by the drain script or stopping gorouter should be done by monit and not the drain script.

**Comment by aaronshurley** [comment]
This work has been completed and will be published with the next final release

**Comment by shubhaat** [comment]
This is included in release [0.180.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.180.0)
