### ISSUE TITLE
TCP Routing release version 0.163.0 - 0.171.0 upgrade issue

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/routing-release#113]
As per cf-deployment channel, they have asked to upgrade the TCP routing release version to 0.171.0 from version 0.163.0 as per CF release version 287. While upgrading from version 0.163.0 to 0.171.0 TCP routing release version, we are getting an error while deploying manifest with 0.171.0 changes.
The error is stated below :

{"timestamp":"1531141476.473280668","source":"routing-api","message":"routing-api.failed-initialize-sql-connection","log_level":2,"data":{"error":"dial tcp: lookup mysql.service.cf.internal on xx.x.x.x ip no such host","host":"mysql.service.cf.internal","port":3306}}

We have configured sqldb credentials for routing_api with the valid host, still, we are facing above error, please provide the appropriate solution as what has to be done to proceed with manifest deployment for 0.171.0.

**Comment by lordcf** [comment]
We are upgrading from TCP routing release version 0.163.0 - 0.171.0, but we are getting error as below when we provide the IP:
	
	{"timestamp":"1531723461.885452032","source":"routing-api","message":"routing-api.failed-initialize-sql-connection","log_level":2,"data":{"error":"TLS requested but server does not support TLS","host":"10.1.5.19","port":3306}}

	When we are providing the hostname instead of IP, we get below error:
	
	{"timestamp":"1531141406.330147743","source":"routing-api","message":"routing-api.failed-initialize-sql-connection","log_level":2,"
	data":{"error":"dial tcp: lookup mysql.service.cf.internal on 10.1.0.2:53: no such host","host":"mysql.service.cf.internal","port":3306}}
	
	In TCP routing release 0.166.0, we tried to dig mysql.service.cf.internal, but we don't get any response. 
	It is mentioned that etcd support is removed, so in place of etcd which component is needed to be configured, to resolve the hostname. And what set of properties need to be added so as to make it resolve the hostname provided.

**Comment by aaronshurley** [comment]
@lordcf It sounds like the mysql DB can't be found at `mysql.service.cf.internal`, do you know how it's being registered? In the latest [cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/521767df78b70219800df340fec40fb34b818b8a/cf-deployment.yml#L180) it looks like the mysql VM's are registering their route as `sql-db.service.cf.internal`. Please let us know if that helps

**Comment by lordcf** [comment]
We have currently upgraded cf-release from v283 to  v287 for production as migration to cf-deployment is in progress. With cf-release v283, we are using routing-release v163. We want to upgrade routing release to v171 for our environments.

In our cf-manifest, mysql db(cf-mysql-release v32) is registered using mysql.service.cf.internal.

We have also tried upgrading one version at a time for routing-release v163 to v164. We are able to deploy tcp-routing deployment after changes. But when we try to curl the application we receive output as`Empty reply from server`. 
We have involved all properties as per the spec including [https://lists.cloudfoundry.org/g/cf-dev/attachment/7102/0/attachment.html](url). 

Any other changes or configuration that need to be added for upgrading from v163 to v171 like changes due to removal of tcp-emitter and etcd properties from routing-api job?

**Comment by lordcf** [comment]
Hi Team,

Above mentioned issue for `dial tcp: lookup mysql.service.cf.internal on 10.1.0.2:53: no such host"` is resolved. But currently it is failing with below mentioned error logs available in routing-api.log

`Started updating instance routing_api_z1 > routing_api_z1/2845bfa6-ea22-4d85-974f-523303cb1650 (0) (canary). Failed: 'routing_api_z1/0 (2845bfa6-ea22-4d85-974f-523303cb1650)' is not running after update. Review logs for failed jobs: routing-api (00:15:42)

Error 400007: 'routing_api_z1/0 (2845bfa6-ea22-4d85-974f-523303cb1650)' is not running after update. Review logs for failed jobs: routing-api`

Error logs in file 

`[2018-07-18 10:34:13+0000] {"timestamp":"1531910053.745829105","source":"routing-api","message":"routing-api.failed-initialize-sql-connection","log_level":2,"data":{"error":"TLS requested but server does not support TLS","host":"mysql.service.cf.internal","port":3306}}
`

**Comment by shalako** [comment]
It appears that the mysql server routing-api is attempting to communicate with does not support TLS.

**Comment by aaronshurley** [comment]
@lordcf are you still encountering issues? if so, a conversation in #routing on slack would probably resolve it more quickly

**Comment by adobley** [comment]
@lordcf Since this issue is a bit stale, I'm going to close it for now. Please re-open or reach out on the cloudfoundry slack #routing channel for more help.

Thanks!
