### ISSUE TITLE
route registrar to register a route on an isolation segment / shard

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/routing-release#115]
## Issue
route registrar should provide a way to configure a route on a given isolation segment

## Context

We have set an internet dedicated isolation segment.
Need to expose a bosh deployment on internet, want to register the route in shared nats server.
Miss a way to indicated related shard.

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

**Comment by shalako** [comment]
Thank you for opening this issue. We've been thinking about this, too, but I don't think we can get to it soon. @aaronshurley would you accept a PR for this?

**Comment by aaronshurley** [comment]
Absolutely!

**Comment by poblin-orange** [comment]
@shalako @aaronshurley  also, i ve seen the ongoing istio refactoring. Are there any plan to offer an equivalent route-registrar for the new routing ?

**Comment by shalako** [comment]
Hello @poblin-orange I expect it will come as no surprise that in our efforts to integrate Istio into CF, we're initially focusing on application use cases, but we have thought a little about how we might leverage Istio for BOSH deployed components also. One option could be to enhance route-registrar, but we have also considered integrating directly with the BOSH director, removing the need for release authors to colocate an additional process. Imagine specifying a need for external routing in your manifest, and the istio-release discovering it from the Director.

**Comment by poblin-orange** [comment]
@shalako interesting. Bosh could be a good place to leverage some istio feature, with bosh-dns, for internal wiring. Even if there is a risk to group too many features in a single component. Globally, we use route-registrar mostly for public exposition of existing bosh release. All the ssl / horizontal scalabilty /  logging features of the routing release are very valuable.

**Comment by shalako** [comment]
Thank you for sharing your use cases, @poblin-orange. We will reach out to you when we get closer to a proposal to enable use of Istio by BOSH release authors. 

Do you expect to contribute a PR for support of isolation segment in route-registrar?

**Comment by poblin-orange** [comment]
@shalako Id love to, but i dont think i can, not proficient enough in go.

**Comment by bruce-ricard** [comment]
We don't have the bandwidth to work on this at the time. Closing since it's been idle for 6 months.

@tstannard and I
