### ISSUE TITLE
Issues flagged by gosec against routing-0.180.0

### ISSUE THREAD

**Issue by Wayne-H-Ha** [cloudfoundry/routing-release#123]
Not sure if the following high severity issues flagged by gosec against routing-0.180.0 are valid? Will they be resolved if they are valid?

```
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"rule_id": "G402",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "./go/src/routing-0.180.0/packages/code.cloudfoundry.org/routing-api/client.go",
			"code": "InsecureSkipVerify: skipTLSVerification",
			"line": "47"
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"rule_id": "G402",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "./go/src/routing-0.180.0/packages/github.com/nats-io/go-nats/nats.go",
			"code": "InsecureSkipVerify: true",
			"line": "914"
		},
		{
			"severity": "HIGH",
			"confidence": "HIGH",
			"rule_id": "G402",
			"details": "TLS InsecureSkipVerify set true.",
			"file": "./go/src/routing-0.180.0/packages/github.com/go-sql-driver/mysql/dsn.go",
			"code": "InsecureSkipVerify: true",
			"line": "531"
		},
```

**Comment by shalako** [comment]
For development environment where self-signed certs are used, having a mode that skips validation of of a cert is helpful. This mode is not the default, and shouldn't be used in production environments.

I'll have the engineering team double check.

**Comment by zachgersh** [comment]
We've taken a look at each of these (two of which are third party dependencies we only vendor).

1. `routing-api` - configurable TLS skip verify for testing
2. `go-nats` - as long as you pass a TLS config you are not insecure true (also configurable)
3. `go-sql-driver` - has configuration to control whether TLS is on or off as well

All instances accept configuration of TLS and are not just default to skip verify all the time.
