### ISSUE TITLE
Operator can specify headers that should be deleted from gorouter responses

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/routing-release#129]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

CF operators have said that it would improve security if they could specify a list of HTTP headers that should be stripped by gorouter from responses returned to downstream clients.

## Steps to Reproduce

Curl any route through gorouter

## Expected result

After configuring a manifest property with `X-Vcap-Request-Id` and deploying, responses should not include `X-Vcap-Request-Id`

## Current result

Currently gorouter returns the HTTP header `X-Vcap-Request-Id`

## Possible Fix

New manifest property

```
router.http_rewrite.responses.remove_headers:
    description: "Array. List of HTTP headers that will be stripped from responses."
```

Usage example
```
  properties:
    router:
      http_rewrite:
        responses: 
          remove_headers:
          - name: X-Vcap-Request-Id
```

**Comment by shalako** [comment]
@keymon Would you be willing to send us PRs for this, too?

**Comment by keymon** [comment]
> @keymon Would you be willing to send us PRs for this, too?

@shalako https://github.com/cloudfoundry/gorouter/pull/234

**Comment by utako** [comment]
Your changes should be in Routing Release 0.183.0. Thanks for your contributions!
