### ISSUE TITLE
Health check script not working in Route Registrar

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry/routing-release#131]
## Issue
Route registration fails with following message
`{"timestamp":"1542181865.543938160","source":"Route Registrar","message":"Route Registrar.Script exited with error","log_level":1,"data":{"error":"exit status 127","script":"/var/vcap/jobs/***/bin/health_check","stderr":"/bin/sh: 1: /var/vcap/jobs/***/bin/health_check: not found\n","stdout":""}}
.....

{"timestamp":"1542181865.544017076","source":"Route Registrar","message":"Route Registrar.healthchecker returned unhealthy for route","log_level":1
...........

{"timestamp":"1542181865.544112921","source":"Route Registrar","message":"Route Registrar.Unregistered routes successfully","log_level":1,"data":{}}`

But the same script ran by following command is working and exiting with code '0'
`/bin/sh var/vcap/jobs/***/bin/health_check`

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

Route registration should be successful and script should return zero status.

## Current result

Route registration not successful and script returns non zero status.

## Relese version:
0.183.0, 0.180.0

Prior to 0.180.0, it used to work. I see in 0.180.0 onwards bpm based job is written. Is bpm internally causing this issue?

**Comment by aaronshurley** [comment]
Hi @sauravmndl, this does sound like it might be related to our integration with bpm. To help us better understand the situation, I think we'll need a bit more information:
- To verify, do you have bpm co-located on this vm?
- Would you mind sharing your `/var/vcap/jobs/job/config/bpm.yml` (feel free to sanitize anything necessary)?

**Comment by sauravmndl** [comment]
Hi @aaronshurley 
1. Yes bpm colocated in the vm.
2. Following is the content of bpm.yml

`
processes:
  - name: route_registrar
    executable: /var/vcap/packages/route_registrar/bin/route-registrar
    args:
    - --configPath
    - /var/vcap/jobs/route_registrar/config/registrar_settings.json

    unsafe:
      unrestricted_volumes:

         - path: /var/vcap/jobs/service-fabrik-broker
           allow_executions: true
         - path: /var/vcap/data/service-fabrik-broker
`

**Comment by utako** [comment]
Hi @sauravmndl,

Could you please share some reproduction steps? 

Thanks,
@utako, CF Routing Team

**Comment by sauravmndl** [comment]
Hi @utako ,

The health check script used is https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/blob/master/jobs/service-fabrik-broker/templates/bin/health_check.erb

It is giving syntax issue at line https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/blob/master/jobs/service-fabrik-broker/templates/bin/health_check.erb#L5

But it passes if I run the script explicitly by `/bin/sh var/vcap/jobs/***/bin/health_check` or `/bin/bash var/vcap/jobs/***/bin/health_check`.

Is bpm somehow causing problem?

**Comment by ameowlia** [comment]
Hello @sauravmndl, 

I noticed that you run the script with `/bin/sh`, but the script shebang is `/bin/bash`. Maybe you don't have bash installed? 
Try to reproduce this error, by running the script like this:
```
var/vcap/jobs/***/bin/health_check
```

Also, you can check if BPM is affecting things, by running the script inside of the BPM container instead of from the VM as root.
If you use the bpm cli (which should be installed) and get into the container for the route_registrar and run the script there, can you reproduce the error? 
```
bpm shell route_registrar
var/vcap/jobs/***/bin/health_check
```

Thanks, 
@ameowlia and @bruce-ricard, CF Networking Program Members

**Comment by sauravmndl** [comment]
Hi @ameowlia,

With 186 release I am not getting the error. Hence closing the issue. If I face further then update/re-open or create a new one.

Thanks,
@sauravmndl
