### ISSUE TITLE
adding Observability as Code to Routing components

### ISSUE THREAD

**Issue by beckettsean** [cloudfoundry/routing-release#151]
## Issue

Not a bug but a feature request:

The [Monitoring Indicator Protocol](https://github.com/pivotal/monitoring-indicator-protocol/wiki) is observability as code, allowing CF components to declare their own monitoring, alerting, and related documentation. 

## Context

In a world where components leverage Indicator Protocol, downstream components or teams aren't stuck deriving or maintaining observability for upstream components. Those with the most expertise in monitoring and alerting on a component are the ones that author the alert queries, dashboards, and docs. These are encoded in a YAML doc that allows many tools, like Grafana, Prometheus Alert Manager, and others that speak PromQL, to automatically observe the component with little or no configuration required by the operator.

## Next steps

We're starting a conversation with Routing engineering after talking with the product team a bit. We'd love to get a convo going with @KauzClay so that we can get a PR ready to address this issue.

**Comment by beckettsean** [comment]
@MatthewARinehart

**Comment by mike1808** [comment]
@beckettsean @MatthewARinehart @KauzClay do you have any updates on this?

Thanks,
@tstannard and @mike1808 , CF Networking Program Members

**Comment by MatthewARinehart** [comment]
Sorry, this was added to my personal GitHub account. I need to have my Pivotal one added:  @mrinehart13

**Comment by mrinehart13** [comment]
And here I am.

We have a story in the Indicator Protocol backlog to create the initial Indicator document for GoRouter, but it has not been started yet. https://www.pivotaltracker.com/story/show/167233624

Is this something that the GoRouter team would like to pair with us on?

**Comment by mike1808** [comment]
@mrinehart13 We need to speak with our PM about this and let you know about updates.

Thanks,
@tstannard and @mike1808, CF Networking Program Members

**Comment by adobley** [comment]
@mrinehart13 We'd be happy to pair on this, when works best for you? Can also reach out on slack if thats easier :D

**Comment by mrinehart13** [comment]
CC: @vreynolds

**Comment by KauzClay** [comment]
Hi all, 

We believe this work has been taken care of here: https://www.pivotaltracker.com/story/show/165610048
The work should be available in the next routing release, [0.191.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.191.0).

We are going to close this, but feel free to re-open if the new release does not address the concerns.

Thanks, 
@tcdowney  and @KauzClay , CF Networking Program Members
