### ISSUE TITLE
Clarify on the usage of multiple app ports

### ISSUE THREAD

**Issue by GFriedrich** [cloudfoundry/routing-release#152]
Hi,

I've recently read about the possibility to use multiple app ports in CloudFoundry and wondered how this can be handled via the CLI.
Unfortunately I've found that this feature has been "abandoned" and the previous CLI implementation has been dropped via https://github.com/cloudfoundry/cli/commit/e9fe2d3cce1dc6463842eb6fc99b993b1af1b355
Shortly afterwards I've found this post in the CloudFoundry mailing list: https://lists.cloudfoundry.org/g/cf-dev/message/8410
This in turn is the complete opposite of what was mentioned earlier on the commit. This is also backed by the PMC meeting notes at https://github.com/cloudfoundry/pmc-notes/blob/master/Runtime/2018/2018-12-11-runtime.md#routing---shannon-coen
To make things even more confusing: Even the latest API documentation (https://apidocs.cloudfoundry.org/10.1.0/apps/updating_an_app.html) contains the experimental flag for the "ports" attribute (so it hadn't been removed as mentioned on the mailing list).

So I'm a bit confused right now. What is the REAL status of this feature?
Stable, experimental, abandoned?!

Because if it is stable, the support in the CLI should return and the flag should be removed from the API documentation. And if it has been dropped, the feature should be removed from the API documentation and the CloudFoundry documentation itself should be adapted.

Maybe @shalako can elaborate on this.
Thank you for any clarification in advance.

**Comment by GFriedrich** [comment]
@mrinehart13 maybe you can give any insight what is going on?
I would really appreciate any information on this. :)

**Comment by KauzClay** [comment]
Hi @GFriedrich , this is definitely confusing! Sorry about that. 

I had to do some digging, but this is in fact stable, no longer experimental. Somehow, the edit to the docs never made it through. I sent a PR to get that fixed here: https://github.com/cloudfoundry/cloud_controller_ng/pull/1410

**Comment by GFriedrich** [comment]
@KauzClay Awesome! Good news. Thank you very much.
Can you tell whether there is a plan to return the feature in the CLI?

**Comment by KauzClay** [comment]
@GFriedrich Unfortunately I don't think there is a plan to add a specific command to the cli for altering ports. CC @adobley if that isn't the case.

 However, in case you didn't know, you can use the cf curl command like [this](https://docs.cloudfoundry.org/devguide/custom-ports.html):
`cf curl /v2/apps/APP-GUID -X PUT -d '{"ports": [PORT1, PORT2, PORT3...]}' `

**Comment by adobley** [comment]
@GFriedrich We've got a couple stories: https://www.pivotaltracker.com/story/show/164742529 https://www.pivotaltracker.com/story/show/164742599 https://www.pivotaltracker.com/story/show/164742660 https://www.pivotaltracker.com/story/show/164742714 https://www.pivotaltracker.com/story/show/164742819 for the CLI. I can't say how soon I expect these though. I have heard there is a community plugin, but haven't seen it myself.

**Comment by GFriedrich** [comment]
@KauzClay Thanks for the hint - this is exactly how I currently configure the ports, but of course some "real deal" in the CLI would be a much better solution.

@adobley I saw those tickets already but none of them mentions the initial creation of an app with multiple ports. As said this feature was there before, but was removed via https://github.com/cloudfoundry/cli/commit/e9fe2d3cce1dc6463842eb6fc99b993b1af1b355
So the first step from my point of view would be to readd this feature and then add the possibility to map routes to specific ports later on (which is mentioned in those tickets).
Anyways, I will check out whether there is some plugin for it. Thanks for the hint.

**Comment by GFriedrich** [comment]
@adobley Yes, it would be definitely preferable that this configuration can be applied via the manifest.
But I think it should also be possible via the CLI arguments.
Basically returning the featureset which was removed by https://github.com/cloudfoundry/cli/commit/e9fe2d3cce1dc6463842eb6fc99b993b1af1b355 would be the perfect solution.

I'm wondering: Is there some GitHub project or responsible group for developing the manifest? Because it is used in several places and I guess it needs some alignment.

I'm also thinking whether the simple "ports" property in the manifest would be a good fit. Normally you want to attach the port to some specific route, so it would be much nicer to have some enhancement of the `routes` property where you can add a port to each route. This would also be a much better fit to the newly designed V3 routes resource of the CF API.

**Comment by GFriedrich** [comment]
@adobley I'm not aware of any documentation - as the feature was hidden all the time due to being in "experimental" phase, I also don't think that there were that many users.
Your example of the manifest was exactly what I had in mind. Having this in the manifest would be perfect for me. At least I don't need to define an app port without any route. Not sure if there is some hidden value for this case though.

By the way: I've opened a PR some time ago to add the port support to the CF Java library (see https://github.com/cloudfoundry/cf-java-client/issues/975). This also added the support of the "ports" attribute for the manifest to the library, but if you're going to use the "routes with ports" approach instead, I would adapt my PR. This is also basically why I was asking for some alignment and was wondering who is responsible for the manifest structure as a whole.

**Comment by sethboyles** [comment]
I would just like to note that implementing routes and ports in manifests are complicated by the fact that routes can have multiple destinations, along with weightings that can be across many apps (and must add up to 100).  So this would require some thought before we implement this in CCNG

**Comment by GFriedrich** [comment]
@sethboyles Ok, just drop me a note once you've decided how the manifest should look like and I will try to help you as good as I can.

**Comment by KauzClay** [comment]
From the above, it sounds like the initial issue to clarify usage of multiple app ports has been resolved. However, there is an open conversation around being able to specify multiple app ports in the app manifest.

If the above is a correct description, perhaps the next step would be to start an issue on [capi-release](github.com/cloudfoundry/capi-release) since the work will need to be done there and use that as the tracking point. If that's agreeable @GFriedrich please let us know so we can close this issue.

Thanks
@KauzClay and @angelachin

**Comment by GFriedrich** [comment]
Hi @KauzClay and @angelachin,
yes, that would be fine for me.
Nevertheless I would appreciate if you could also talk to @abbyachau whether there is already some ticket on this "routes and ports in the manifest"-userstory. I've recently answered her question on Slack, what my usecase on this feature is, but got no response.
Would be great if I could have some place where I can see the progress on this story (and possibly help out, if you want me to).
Regards,
@GFriedrich

**Comment by abbyachau** [comment]
Hi @GFriedrich thanks, I'm just seeing this thread for the first time. The v3 Acceleration Team added supported on v3 for custom app ports but the CLI have not been asked to support the feature. @adobley please reach out about this so we can prioritise accordingly. 

The v3/v7 manifest is now owned by the CC API team. They would be your liaison for the manifest support.

**Comment by GFriedrich** [comment]
Hi @abbyachau,
oh, I guess we missed each other in the Slack thread then.
Anyways: I guess, I will open an issue on the CAPI project then. Let's see how things move forward over there.
Thanks for all your help here! Appreciate it!
