### ISSUE TITLE
Route-registrar job changes on every deploy when routing-api disabled

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/routing-release#155]
Route-registrar job changes on every deploy when no manifest changes

## Issue

We have disabled routing-api and the new code to allow this is now causing the route-registrar to have differences on every bosh deploy.  This causes many vms to be updated when they do not require it.

## Context

The certs files from route-registrar are looking different to bosh which makes them cause an update to the vm.

## Steps to Reproduce

Disable routing-api and do back to back deploys with no differences.  All vms with the route-registrar job are being updated due to differences in a comment in the certs files.

## Expected result

back to back deploys with no differences should not update vms.

## Current result

Here . is the DIFFS ...
```
diff -r 6b5c749c8dbef4bda2639f1e774a816b57b1def8/ da9900d59dbd6c22727505213f9c1df0bf96a119/
diff -r 6b5c749c8dbef4bda2639f1e774a816b57b1def8/config/routing_api/certs/client.crt da9900d59dbd6c22727505213f9c1df0bf96a119/config/routing_api/certs/client.crt
1c1
< #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007f90e090f7e0>
\ No newline at end of file
---
> #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007fb0dc7eaee8>
\ No newline at end of file
diff -r 6b5c749c8dbef4bda2639f1e774a816b57b1def8/config/routing_api/certs/server_ca.crt da9900d59dbd6c22727505213f9c1df0bf96a119/config/routing_api/certs/server_ca.crt
1c1
< #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007f90e090c478>
\ No newline at end of file
---
> #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007fb0dc7f3ed0>
\ No newline at end of file
diff -r 6b5c749c8dbef4bda2639f1e774a816b57b1def8/config/routing_api/keys/client_private.key da9900d59dbd6c22727505213f9c1df0bf96a119/config/routing_api/keys/client_private.key
1c1
< #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007f90e090da58>
\ No newline at end of file
---
> #<Bosh::Template::EvaluationContext::ActiveElseBlock:0x00007fb0dc7e99d0>
\ No newline at end of file
```

## `name of issue` Output Results

**Comment by adobley** [comment]
Hi @andrew-edgar 	
The fix for this is in 0.191.0 of routing-release!

Thanks for reporting this and helping us out.
