### ISSUE TITLE
Routing-api needs properties to set min and max db connections

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/routing-release#156]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We need to have the routing-api components have a min and max connection pool for the databases as having possibly unlimited connections will not allow our DB team to size and enable the routing-api database.

## Context

All other components talking to database instances in CF have a min and max connection pool settings. 

## Steps to Reproduce

There is no bosh properties to set and the team said there will be an unlimited MAX connections

## Expected result

The operator can set properties to set the max connections and there is a reasonable limit by default.

## Current result

Possible to have too many connections to the DB

**Comment by andrew-edgar** [comment]
Yeah that all would definitely make sense.  Thanks the more flexibility to be able to configure the connections to the DB the better!

**Comment by adobley** [comment]
@andrew-edgar We just released this functionality in https://github.com/cloudfoundry/routing-release/releases/tag/0.196.0!

🎉 🎈 🎈 🎉 

Let us know when you get a chance to try this out if it addresses your needs.

Thanks!

**Comment by KauzClay** [comment]
Hey @andrew-edgar ,

As Aidan mentioned above, we released this functionality in 0.196.0. We are going to close this issue now, but feel free to reopen if the current functionality doesn't meet your needs.

Best,
Clay and @adobley
