### ISSUE TITLE
Cloud Foundry on Huawei china cloud(Openstack) not accessible outside VPC.

### ISSUE THREAD

**Issue by mandar14** [cloudfoundry/routing-release#161]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Cloud Foundry on Huawei china cloud(Openstack) not accessible outside VPC.

## Context

We have deployed CF v12.10 with HAproxy, all default settings, and credhub created self-signed domain certs.
Post successful deployment we can access CF api from Huawei VPC with --skip-ssl-validation.
Able to target and push application. (cf api ,login, create-space, push <app> etc)

But simillar CF api commands are not working from Public internet (my machine or AWS vm with public IP).

Initially I thought some issue with HAproxy, hence I bring my Router vm in DMZ with public IP.
Now  Traffic directly goes from Internet to Router, producing same error.

not able to understand this behaviour.  Following are logs from various system.

**curl from public internet(AWS)**
curl -vvv https://api.sys.cf.cloud.com -k
* Rebuilt URL to: https://api.sys.cf.cloud.com/
*   Trying 1xx.xx.xx.xx2...
* TCP_NODELAY set
* Connected to api.sys.cf.cloud.com (1xx.xx.xx.xx2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**resulting log at Gorouter:  gorouter stderr**
2019/12/16 09:11:25 http: TLS handshake error from <aws-public-ip>:58340: write tcp 10.100.6.61:443-><aws-public-ip>:58340: write: connection reset by peer

**Comment by KauzClay** [comment]
Hey @mandar14 ,

Sorry for the slow response on this 😬 

After taking a quick look, we have a couple questions. The first being, is this still happening?

If so, we were concerned about the TLS version error. We had two thoughts. 
1. We currently do no support TLS1.3. Is your HAProxy or browser trying to use TLS1.3? Could you force it to use TLS1.2 and see what happens?
1. Are there any more logs with your HAProxy? The "connection reset by peer" line makes it seem like the HAProxy reset the connection. Perhaps it didn't get the response it was expecting?

Best,
Clay and @adobley , CF Networking Program

**Comment by mandar14** [comment]
Hello Clay, 

As mentioned previously, using standard HAProxy release from community nothing changed.

Anyways as  a workaround we Opted for Cloud Provider LB instead of HAproxy. Since its in China region, standard 80,443 ports are not accessible.We set custom 3443 port for API and Apps and added listener for same. This gives rise to another issue UAA always listen only on 443.

Considering  CAPI is only component taking to UAA  and it within VPC.we have to add 443 listener to LB also.

Now we set api on `API.domain.com:3443`, which goes to `UAA.domain.com:443` for authentication.
And apps are worldwide accessible on  `APP.domain.com:3443`.

Not the best solution, but considering work needs to be done from Chinese geography only it working.

Thanks for your support, will bug any for next issue  ;)

**Comment by KauzClay** [comment]
Hey @mandar14 

Sorry about that inconvenience, but we're glad you found a way around. It sounds like you are good now, so we're gonna close the issue. Feel free to reopen it, or make a new one, if you have any more problems.

Best,
Clay and @adobley , CF Networking members
