### ISSUE TITLE
Replace uaa-go-client with alternative

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/routing-release#163]
## Issue

The [`cloudfoundry-incubator/uaa-go-client`](https://github.com/cloudfoundry-incubator/uaa-go-client) library is no longer maintained. In the various components of `routing-release` that currently use `uaa-go-client`, we should replace our usage with something that is maintained, perhaps [`cloudfoundry-community/go-uaa`](https://github.com/cloudfoundry-community/go-uaa).

## Context

Recently, we closed a few issues on the `uaa-go-client` repo as "wontfix" that were years old, with comments from as long ago indicating that we planned to deprecate that library. We have not updated the README for the client to indicate it is no longer maintained. Since then, a new, community-supported library exists that may be a viable alternative worth considering: [`cloudfoundry-community/go-uaa`](https://github.com/cloudfoundry-community/go-uaa).  

## Additional Context

Files that reference `uaa-go-client` in `routing-release`, as of today:

```
scripts/run-all-component-tests.sh
packages/route_registrar/spec
packages/tcp_router/spec
packages/rtr/spec
packages/gorouter/spec
packages/acceptance_tests/spec
packages/routing-api/spec
src/code.cloudfoundry.org/route-registrar/routingapi/api.go
src/code.cloudfoundry.org/route-registrar/routingapi/routingapi_test.go
src/code.cloudfoundry.org/route-registrar/main.go
src/code.cloudfoundry.org/cf-tcp-router/watcher/watcher_test.go
src/code.cloudfoundry.org/cf-tcp-router/watcher/watcher.go
src/code.cloudfoundry.org/cf-tcp-router/routing_table/updater.go
src/code.cloudfoundry.org/cf-tcp-router/routing_table/updater_test.go
src/code.cloudfoundry.org/cf-tcp-router/main.go
src/code.cloudfoundry.org/gorouter/route_fetcher/route_fetcher.go
src/code.cloudfoundry.org/gorouter/route_fetcher/route_fetcher_test.go
src/code.cloudfoundry.org/gorouter/main.go
src/code.cloudfoundry.org/routing-api-cli/main.go
src/code.cloudfoundry.org/routing-api/cmd/routing-api/main.go
src/code.cloudfoundry.org/routing-api/handlers/routes_handler.go
src/code.cloudfoundry.org/routing-api/handlers/event_stream_handler_test.go
src/code.cloudfoundry.org/routing-api/handlers/tcp_route_mappings_handler.go
src/code.cloudfoundry.org/routing-api/handlers/router_groups_handler_test.go
src/code.cloudfoundry.org/routing-api/handlers/event_stream_handler.go
src/code.cloudfoundry.org/routing-api/handlers/router_groups_handler.go
src/code.cloudfoundry.org/routing-api/handlers/routes_handler_test.go
src/code.cloudfoundry.org/routing-api/handlers/tcp_route_mappings_handler_test.go
src/code.cloudfoundry.org/routing-acceptance-tests/helpers/test_helpers.go
```

**Comment by KauzClay** [comment]
adding the `help wanted` label, as we do plan to get to this at some point, but we would also welcome anyone to do it as a PR.

**Comment by MarcPaquette** [comment]
This work is completed within the routing release
