### ISSUE TITLE
Clarify that `request_timeout_in_seconds` configures both a "backend idle timeout" and a "request timeout"

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/routing-release#167]
## Issue

The `request_timeout_in_seconds` spec property description is incomplete. Until recently, it only mentioned how it configures a per-request timeout. Then recently, [it was updated](https://github.com/cloudfoundry/routing-release/commit/f6ea24cbf6b6d26e946e3e862a468c59e6a6b611) to indicate that it configures a backend idle timeout. In fact, it does both and should be updated to reflect that fact.

In addition, it would be helpful to have tests that demonstrate this behavior more clearly.

## Context

In a recent exploration to determine what was causing slower drain times on a particular deployment, we were testing the interaction between `drain_timeout` and `request_timeout_in_seconds` and thought that `request_timeout_in_seconds` just didn't work. 

In retrospect, this was likely because we were misconfiguring it as we were also configuring `router.drain_timeout`. After verifying the `request_timeout_in_seconds` _does_ work, we think the reason we didn't see it working earlier was either because we were incorrectly nesting it under `router`, or because we were forgetting to add `_in_seconds`, or both. We have since verified that it works and is wired up correctly in TAS.  While it may be nice to make these properties more consistent, changing BOSH spec properties is a breaking change, so we don't intend to do that any time soon.

We then rediscovered that the setting for `request_timeout_in_seconds` gets mapped to `EndpointTimeout` in the `gorouter` configuration. This in turn is used for two things:

1. a backend idle timeout, implemented in `router/router.go`, and 
2. a request timeout, implemented in `proxy/round_tripper/proxy_round_tripper.go`. 

At some point in our investigation, we believed that it was _only_ configuring a backend idle timeout, but we now have seen that it is both.

We are going to add a couple tests that make this more clear and update our spec property descriptions to match.

## Additional Context

Related PR from the past: https://github.com/cloudfoundry/gorouter/pull/211

**Comment by jrussett** [comment]
Hi! 

This issue has been resolved in [Release 0.202.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.202.0). 

Thanks,
Josh R.
