### ISSUE TITLE
fork a new HAProxy only when configuration has changed

### ISSUE THREAD

**Issue by larham** [cloudfoundry/routing-release#169]
The "sync" timer currently forks a new HAProxy instance every minute, by default. (This may be a way to adapt to any new network route that might appear.)

However, any previous HAProxy gets "gracefully" terminated, meaning that it can live as long as any client has an active connection to it.  In the case of a client with a long-lived connection, this implies that RAM usage can go up infinitely.

Proposed Resolution
The tcp-router job should only invoke the haproxy-reloader script to create a new instance if the TCP route configuration has changed.

Can this feature be added?

(Issue description edited slightly by @jenspinney & @christianang)

**Comment by mcwumbly** [comment]
Hey @larham, thanks for reporting this issue. We are digging deeper into this and considering your proposed resolution. 
 We'll update this issue again when we have more information to share about next steps.

**Comment by jrussett** [comment]
Hi @larham. 

We integrated this feature in [Routing Release `0.204.0`](https://github.com/cloudfoundry/routing-release/releases/tag/0.204.0).

Apologies for not mentioning this earlier. Thank you for opening this issue.
- @jrussett
