### ISSUE TITLE
gorouter: consider removing/replacing the /healthz endpoint

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/routing-release#175]
## Issue

The gorouter exposes both `/health` and `/healthz` endpoints for health checking by a load balancer.  Despite the similar names, selecting the wrong one can have a disastrous impact on the availability of applications behind the router.

`/healthz` is hard coded to always report that the router is healthy and ready to receive traffic under any circumstances.  As long as the gorouter process is running, its `/healthz` endpoint will advertise to the load balancer that the router should receive traffic.

The issue with this is there's a common scenario where a router is running, but should not accept traffic - and that's when a router is draining traffic prior to going down for a patch or update operation.  During this time, if the router actually receives end-user traffic, it will fail to service the requests and send back a 5XX error.  The more connections that the router has to drain, the longer the router is in a state of incorrectly reporting health, and the greater impact to applications.  For example, if one router is drained at a time, then 1/Nth of traffic to applications will fail for M*N minutes, where N is the number of gorouters behind the load balancer and M is the number of minutes it takes for a router to drain and shut down.  For an environment with 3 routers that take 10 minutes each to drain, you'll experience roughly 33% of your traffic resulting in errors for a cumulative total of 30 minutes (10 for each router).

Unfortunately, long drain times are much more likely in production environments taking lots of traffic, so we have an issue that is both:

- very easy to accidentally misconfigure, and
- much more likely to affect high-traffic production environments than smaller sandbox/dev environments 

## Context

The `/health` (not `/healthz`) endpoint was introduced [4 years ago](https://github.com/cloudfoundry/gorouter/commit/a36a7ab860ce03d0ca397c7c4b9d370a3477005a), and functions correctly when the router is draining by returning 503s to the load balancer instead of hard coded 200s.

The [README](https://github.com/cloudfoundry/gorouter#healthchecking-from-a-load-balancer) has a note describing the `/healthz` deprecation:

> DEPRECATED: The /healthz endpoint provides a similar response, but it always returns a 200 response regardless of whether or not the GoRouter instance is healthy.

This is helpful, but I only found it after an outage.  I think we can do better.  To me, this note is:

1. Not worded strongly enough.  It mentions a deprecation, but doesn't mention any potential impact to availability, and doesn't even recommend that `/healthz` should be avoided, it just describes it as issuing a "similar response."
2. Not visible enough for customers of commercial platforms based on gorouter to actually protect them from being impacted.

If the purpose of the deprecation note was to inform people that the endpoint may be removed or replaced in the future, it seems like we have plenty of grounds to do just that.

## Steps to Reproduce

1. Configure load balancer to health check on port 8080 at endoint `/healthz`.
1. Ensure that >1 healthy routers are placed behind the load balancer.
1. Force a router to drain, for example via `bosh -d cf recreate router/0`.  It's helpful if this router is takings lots of traffic and will take some time to drain.
1. Monitor load balancer logs and application availability while the router is draining.

## Expected result

Expect that load balancer logs show the router go from healthy to unhealthy while the router is draining and being recreated, and then from unhealthy back to healthy when the new router comes up in its place.

Expect no impact to applications if there are other routers behind the load balancer, as those routers are not being recreated and should be able to handle router/0's load while it is draining. 

## Current result

Load balancer logs show the router reporting healthy for the majority of the drain operation, and only briefly going unhealthy when the instance is destroyed before showing healthy again as the new instance comes up.

1/Nth of traffic to an application behind gorouter results in an HTTP 500 error rather than making it to applications.

Here's an example of an AWS load balancer observing this:
<img width="1374" alt="Screen Shot 2020-07-13 at 4 27 57 PM" src="https://user-images.githubusercontent.com/7527103/88115151-c2046680-cb72-11ea-9648-b7c5110d76a0.png">

In this example, there were 3 routers.  The first router finished its update around 20:55, and the 2nd router began to drain immediately after that.  The 2nd router's health checks didn't start to fail until it finished draining around 21:01, so for the 6ish minutes from 20:55 to 21:01 the load balancer was sending traffic to a router that was unable to process it.  This same behavior occurs for each of the 3 routers.  You would expect the peak of the unhealthy hosts count to sit at 1 for the majority of this 6 minute timeframe.

Note that if this process is repeated after changing the load balancer health check endpoint to `/health` then the expected behavior is observed.

## Possible Fix

I propose keeping the `/healthz` endpoint in gorouter so that any existing load balancers using this endpoint will continue to be function, but make it an alias for `/health` under the hood, so that it correctly reports whether the gorouter is able to serve traffic or not.  Users then can elect to health check against `/healthz` or `/health` and will get equivalent behavior in both cases.

If this is not acceptable, we could consider adding a warning that gets emitted to the logs when `/healthz` is accessed.  There's a chance a log aggregation system may pick this up and alert operations teams to make a change to their load balancer configuration.

## Additional Context

[Commit history](https://github.com/cloudfoundry/gorouter/blame/1680edb697a0edc6c8e37b9d691e24cad0df2f08/common/component.go#L209-L213) shows `/health` has been around as a `/healthz` replacement for 4 years.

**Comment by mcwumbly** [comment]
Additional context: here's a link to the story that added the `/health` endpoint: https://www.pivotaltracker.com/n/projects/1358110/stories/130398331

Note:

> Document that `/healthz` endpoint will be removed soon.

The proposed fix seems reasonable to me on a first reading of this issue.
