### ISSUE TITLE
gorouter: Session Affinity is broken sometimes

### ISSUE THREAD

**Issue by Lindaaaaaa** [cloudfoundry/routing-release#176]
## Issue

Recently, our application experienced requests for one instance suddenly get routed to other instances, causing requests failure. As an example, the request was handled by instance 1 before and all of a sudden, the request was routed to instance 0 even though VCAP_ID is the same as before in the request. 

_Request routed to instance 1_
![requestinstance1](https://user-images.githubusercontent.com/13597751/88311104-567ede00-ccc5-11ea-9a16-015a8afd0735.PNG)

_Request routed to instance 0 all of a sundden_
![requestInstance0](https://user-images.githubusercontent.com/13597751/88311497-ce4d0880-ccc5-11ea-9138-416c72fba319.PNG)

## Context

I have been researching cf go router doc, and it seems go router will route to another instance if the targeted instance is unresponsive or unhealthy. 

Two things we have done so far

1) We have been looking at the instance monitoring metric. There was no crash, memory usage, CPU usage and etc are also fine. Also, cf container will restart the application if it thinks the instance is in unhealthy state, but we do not see instance get restarted, and the instance is still processing new requests. See diagram below:
![july16instance10](https://user-images.githubusercontent.com/13597751/88312320-db1e2c00-ccc6-11ea-8adf-94db59b39bec.PNG)

2) We have also trying to make our node js application sleep (not responsive as quick), and also tried to return 502 constantly. However, we could not reproduce requests routed to another instance behavior. 

**Therefore, we have a question for go-router team**
1) What is the criteria for go router to determine if an instance is not in a healthy state and not routing requests to it
2) If you think it is our application issue, what metrics do you think we should like at 
3) Is this a potential bug in go router side? 

## Steps to Reproduce

N/A

## Expected result

 Session Affinity works as long as instance is healthy

## Current result

Session Affinity is broken

**Comment by ameowlia** [comment]
Hi @Lindaaaaaa, 

Thanks for submitting this issue. 

Can you please ...
1️⃣  - tell us what version of cf-d (if you are using cf-d) you are using and what version of routing-release you are using
2️⃣  - provide a diagram of the traffic from the client to the app. 

For example, the diagram might be as simple as ...
```
          +--------+    +----------+     +-------+
 \o/      |        |    |          |     |       |
  |  +--->+ AWS LB +--->+ Gorouter +---->+  App  |
 / \      |        |    |          |     |       |
client    +--------+    +----------+     +-------+

```

...or maybe you have other things in the path, like route services and additional load balancers.

Here's my favorite [ascii diagram generator](http://asciiflow.com/).

Thanks!
Amelia, CF Networking Engineer

**Comment by KauzClay** [comment]
Hi @Lindaaaaaa ,

> What is the criteria for go router to determine if an instance is not in a healthy state and not routing requests to it

Basically, the gorouter just attempts to make a connection to the backend. Depending on the error, it may or may not be considered retriable by gorouter. If it is retriable, then gorouter will try another instance, which could result in the situation you observed. 

> If you think it is our application issue, what metrics do you think we should like at

It seems like you are observing many metrics already, and those would be what we suggest. You could also check gorouter log messages if you have access. 

> Is this a potential bug in go router side?

We will need the answers to Amelia's questions above, as well as your help to do a deeper investigation in order to determine this.


We are going to close this issue for now. Please reopen the issue if it happens again or you have more information.

Thanks!
Clay & @mcwumbly
