### ISSUE TITLE
Gorouter has no TLS handshake timeout

### ISSUE THREAD

**Issue by mdelillo** [cloudfoundry/routing-release#177]
## Is this a security vulnerability?
No

## Issue
When the gorouter tries to connect to a backend, it will hang for up to [`request_timeout_in_seconds `](https://github.com/cloudfoundry/routing-release/blob/62024aaafec44f0dfc8846aae91d10ad4f66fec4/jobs/gorouter/spec#L293) (default of 15 minutes) even if it cannot establish a TLS connection. It will also not prune the route after getting that error.

## Affected Versions
All

## Steps to Reproduce
1. Push a 1 instance app
1. Find the TLS Host port for the app
1. SSH to the cell it is running on and stop the route emitter with monit
1. On the cell, start netcat to listen on the TLS Host port (just a TCP listener): nc -l <PORT>
1. Curl the app
1. Wait 15 minutes
1. See a 502 from gorouter
1. Check gorouter’s routing table and see the route still exists

## Expected result

* Curl fails with a 502 quicker than 15 minutes
* The route is pruned
* Router logs contain `net/http: TLS handshake timeout`

## Current result

* Curl fails with a 502 after 15 minutes
* The route is not pruned
* Router logs contain `context deadline exceeded`

## Possible Fix

By setting a `TLSHandshakeTimeout` [here](https://github.com/cloudfoundry/gorouter/blob/6af365bbbc3e6dbb5267b1ca47ec5460808a6837/proxy/round_tripper/dropsonde_round_tripper.go#L45-L53), the request will fail much quicker if the TLS connection cannot be established. The error returned will be `net/http: TLS handshake timeout` which can be added [here](https://github.com/cloudfoundry/gorouter/blob/6c9ba7c9207efe4b3d3993ebfa2574ca880f5754/proxy/fails/classifier_group.go#L5-L12) to prune the route.

## Additional Context

One way we think this could occur is:
1. Cell A is running LRP ɑ
1. The route-emitter and rep stop running (there is some networking partition/flakiness)
1. BBS transitions ɑ from Ordinary to Suspect and creates a new unclaimed LRP β
1. Cell B claims and starts a new LRP β
1. The BBS emits an ActualLRPChanged event to signal that LRP β is healthy and an ActualLRPRemoved event to signal that LRP ɑ is going away.

In local Route Emitter mode, each cell subscribes to its events only. If Cell A continues to be down partitioned when the BBS emits the event, then Cell A will not process the event, and the remaining cells will ignore the event. This leads to a stale endpoint in the routing table with no way to prune it. This allows a new app to be allocated the ports of the stale route.

@cloudfoundry/cf-diego

**Comment by jvshahid** [comment]
Does this suggestion assume that Envoy will finish the handshake before trying to connect to the application? Otherwise, an app that is busy or taking longer than expected to process a request could be removed from the routing table.

Assuming that Envoy exhibits the above behavior, is it an implementation detail or part of Envoy's contract?

**Comment by jvshahid** [comment]
I haven't had time to run experiments to verify Envoy's behavior, but I wanted to share my thoughts until I had time to run an experiment.

**Comment by flawedmatrix** [comment]
I think there are two potentially concerning cases to deal with if we do set a TLS handshake timeout:

1. The backend app could become too busy to accept new connections.
2. The backend app could be taking a very long time to return a response to requests (e.g. with heavy database queries).

For the first case, I believe if envoy is responsive, it would report an unhealthy upstream. So it would accept the TLS connection and return a 503. However, if envoy ends up becoming unresponsive as well, then the question becomes whether or not the TLS handshake timeout includes the dial timeout. Based off reading the [Golang source code](https://github.com/golang/go/blob/6f08e89ec3280bf6577c2bdb01243cbeeb1a259d/src/net/http/transport.go#L1500), it looks like the timer for TLS handshake timeout only begins after the connection is established.

For the second case, I believe the TLS handshake would be established before waiting on a response from the backend.

If these assumptions are correct, then I believe the TLS handshake timeout shouldn't affect correctly behaving applications.

**Comment by aminjam** [comment]
For the Steps to Reproduce in the issue, we believe there should be an extra step between 4 & 5, and that's the restart of the app (`cf restart`)

**Comment by sunjayBhatia** [comment]
> For the Steps to Reproduce in the issue, we believe there should be an extra step between 4 & 5, and that's the restart of the app (`cf restart`)

You are correct, we did miss a step there, we issued a `cf stop` between steps 3 and 4 (stop the app before we set up `nc` to listen)
