### ISSUE TITLE
VCAP_ID and JSESSIONID cookies have different expirations

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry/routing-release#182]
## Issue
Users have reported issues when using single sign-on flows backed by UAA with sticky sessions. Currently VCAP_ID has no expiry set, and thus is a session cookie. JSESSIONID (as set by UAA when using sticky session) has an 8 hour expiry.

## Affected Versions

Browser: Internet Explorer
Routing Release: All versions

### What happens from user experience
1. User logs into app using SSO in internet explorer. 
1. User closes and then reopens browser. 
1. User attempts to access application behind SSO.
1. User expects to continue to be able to access the app, but instead is redirected to the login page of SSO

### What should happen from user experience
1. User logs into app using SSO in internet explorer.
1. User closes and then reopens browser. 
1. User attempts to access application behind SSO.
1. User is able to access the app.

### What is going wrong under the hood
1. User logs into app using SSO in internet explorer.
    * This sets the JSESSIONID and VCAP_ID cookie.
1. User closes and then reopens browser.
    * JSESSIONID cookie is still present. VCAP_ID cookie is not present.
1. User attempts to access application behind SSO.
    * Application redirects to random UAA for SSO.
    * (A) If the UAA instance that is chosen happens to be the one that matches the JSESSIONID, then UAA responds without adding the JSESSIONID cookie to the response.
    * Gorouter does not add the VCAP_ID to the response, since there is no JSESSIONID.
    * On the next redirect in the auth flow, a random UAA instance is chosen. 
    * (B) If the UAA instance that is chosen, is not the same as the UAA chosen from the previous step, then it will not be able to successfully authorize the user.
1. User expects to continue to be able to access the app, but instead is redirected to the login page of SSO

The issue does not occur 100% of the time because it depends on the number of UAA instances and which instances are hit in the SSO flow. In the steps, above `A` must be the instance that matches the JSESSIONID in the request and `B` must be a different instance. For reasons that we are unable to explain we are only able to reproduce this in internet explorer. 

## Proposed Solution

When Gorouter inspects the JSESSIONID cookie on the response and sets the VCAP_ID cookie, then it will set the VCAP_ID cookie to have the same expiration as the JSESSIONID cookie. This way both cookies should persist in the browser for the same amount of time.

**Comment by ameowlia** [comment]
## Soliciting Feedback

⚠️ Warning⚠️: This proposal is a change to long standing behavior of how sticky sessions are incremented in gorouter. We have not been able to imagine cases where this change would negatively impact anyone, but it is plausible that someone is relying on the current behavior. In the past we [have made changes to cookies](https://github.com/cloudfoundry/routing-release/issues/170) that hurt apps in unexpected ways.

We would like to solicit feedback from the community, especially those who were involved in the other issue, to double check our assumption that this is a safe change to make.

cc: @stefanlay, @a09-capf, @thomas-kaltenbach, @domdom82

**Comment by ameowlia** [comment]
Here is our proposed solution: https://github.com/cloudfoundry/gorouter/commit/ad7e2a01c67866f4ed18c266e1ba9b5b87938a52

**Comment by domdom82** [comment]
I think this makes sense. The original fix we needed was about the `samesite` attribute missing on vcap_id that prevented iframe integration with another site. So that should be unaffected by this change.

**Comment by ameowlia** [comment]
Thank you @domdom82 for your comment. We are moving forward with this change - https://github.com/cloudfoundry/routing-release/commit/6781c23dedd451c0146e3b1d78d5bb04f64b2249

**Comment by jrussett** [comment]
Hi 👋

A fix for this issue was released in [Routing Release `0.208.0`](https://github.com/cloudfoundry/routing-release/releases/tag/0.208.0).

Thanks!
