### ISSUE TITLE
Bug: gorouter and routing-api may get stuck on requests to UAA

### ISSUE THREAD

**Issue by giner** [cloudfoundry/routing-release#186]
## Issue

gorouter and routing-api don't timeout on requests to UAA and may get stuck

## Affected Versions
The latest versions are suspected to have this issue but not confirmed

## Context

I have a single instance SCF setup (on microk8s) and noticed that gorouter and routing-api don't come back on VM reboot. Investigation showed that gorouter and routing-api don't timeout on requests to UAA. Here what happens when on start:

1. UAA is not running yet however scf.uaa.DOMAIN:2793 is listening, i.e. we can connect to the port, but if we make a request to this endpoint it would be waiting for the response forever (to simulate this behaviour without k8s one could stop uaa and start `nc -kl UAA_PORT`)
2. gorouter and routing-api start and try to access UAA, get stuck on requests to UAA but recognized by monit as running (processes don't crash), gorouter and routing-api don't listen on 8000 and 3000 respectively at this point
3. UAA starts and able to respond to requests however gorouter and routing-api never retry as their initial requests to UAA have got stuck
4. Restarting gorouter and routing-api make them work again until the next restart of the whole system where gorouter and routing-api start before UAA do

## Steps to Reproduce

1. Stop UAA
2. **Make sure that `curl`-ing to the UAA endpoint is not rejected and gets stuck instead**
3. restart gorouter and routing-api
4. Start UAA

## Expected result

gorouter and routing-api start working after UAA is back

## Current result

gorouter and routing-api are running but don't listen on the main ports

## Possible Fix

Potential around: make gorouter and routing-api restart if they don't listen on their main ports for some time
Potential fix: configuring timeouts for requests to UAA

## Additional Context

The following links couild be related to the issue:
- https://github.com/cloudfoundry-incubator/uaa-go-client/blob/19a7eb57a1dcaae620209ecc14f45223d7513a18/config/config.go#L11
- https://github.com/cloudfoundry-incubator/uaa-go-client/blob/19a7eb57a1dcaae620209ecc14f45223d7513a18/config/config.go#L24
- https://github.com/cloudfoundry/gorouter/blob/f7cdb60584a06c9c62a333962fbdc4205c0c0f68/main.go#L389-L398
- https://github.com/cloudfoundry/routing-api/blob/bf245c449fa19c97c7b2500aa65f65206224f7ee/cmd/routing-api/main.go#L321-L325

**Comment by ctlong** [comment]
Initial thoughts:
* I don't know how well routing-release is expected to work on SCF.
* The linked code definitely seems to indicate that the routing-api and gorouter don't timeout on requests to UAA, which is probably something that should be changed.

**Comment by MarcPaquette** [comment]
Hi @giner,

We've done some significant changes to some of the implementation details within our routing-release.  Perhaps due to that, we are unable to reproduce this issue at this time.

Please let us know if you run across this issue again along with reproduction steps.

Thanks,
@MarcPaquette 

CC: @geofffranks
