### ISSUE TITLE
Question - configuring the cookie name can you provide an example? 

### ISSUE THREAD

**Issue by frantzyy** [cloudfoundry/routing-release#188]
## Question

In reference to this...
> You can configure the cookie names that the routing tier uses for sticky sessions by editing the router.sticky_session_cookie_names config key in the deployment manifest.

Can you provide an example of setting the sticky session cookie name to something else?

Is it in the application deployment.yml or is this a configuration on the gorouter itself? 

I tired this in my application deployment.yml and it didn't seem to pick it up..

```
router:
      sticky_session_cookie_names: mystickysessionsid
```

**Comment by ameowlia** [comment]
Hi @frantzyy , 

It is an array, so you would need something like: 

```
router:
      sticky_session_cookie_names: ["mystickysessionsid"]
```

Please reopen if this does not fix your issue.

**Comment by frantzyy** [comment]
Thank you... I'm still testing it out. 

I also have reverse proxy in play deployed by cloudfoundry so I could also be running into the issues stated in this ticket https://github.com/cloudfoundry/routing-release/issues/170.

Thanks again.

**Comment by ameowlia** [comment]
Hi @frantzyy, 

I assume that the reverse proxy is a route service? If so, we have done an investigation into this and plan on fixing sticky sessions with route services soon. 

Investigation doc: https://docs.google.com/document/d/1PpKNpwQVQOwPym_Mzl4O2qM3lh3mcmBHxIvPbYvRw6M/edit#

**Comment by frantzyy** [comment]
It's not. I'll need to investigate that as an option as I'm not that familar with using route services, I've only used services for a redis session and cache.

My current setup looks like this..

Client --> gorouter --> node app (acting as reverse proxy and creating a custom session cookie) --> gorouter --> nginx loadbalancer --> web app (not in cloudfoundry, onprem and creating a JSESSIONID)

My goal is to provide mulit-session support of my onprem web app by maintaining a map of the web app JSESSIONIDs in a parent session using express (which is the reverse proxy).

If I disable the mapping of JSESSIONID to the parent session and allow it to flow through to the client everything works except I don't have multi-sessions because now the browser is tied to that one JSESSIONID.

If I enable the mapping of JSESSIONID to the parent session and only allow the parent express cookie to the client the session affinity is getting lost, even after setting this in both my reverse proxy deployment.yml and my nginx deployment.yml.

```
router:
      sticky_session_cookie_names: ["mystickysessionsid"]
```

Hope that makes sense or at least a little more context.
