### ISSUE TITLE
Provide http traffic shadowing option for blue / green / yellow scenarios

### ISSUE THREAD

**Issue by pauldavidgilligan** [cloudfoundry/routing-release#191]
## Is this a security vulnerability?

No.

## Issue

For spring boot applications there are solutions available to provide http traffic shadowing which is very useful when you would like to send for example 10% of your production traffic to yellow, HaProxy 2.0 also provides this option https://www.haproxy.com/blog/haproxy-2-0-and-beyond/.

Have you such a feature on your road map? This would be a simpler option rather than implementing other cluster / software solutions in some cases maybe. 

## Affected Versions

N/A

## Context

We have a 24 x 7 application suite that requires a low level of outage during upgrades and so we would like to introduce a canary process whereby we can upgrade a smaller sub-set of our applications into product and test these with for example 10% of the production traffic over an extended period of time. After approval of the upgraded applications we would then return to the normal 100% traffic to either blue or green. 

## Traffic Diagram 

user ---|----> 100% http ---------> green
            |---->  10% http ----------> yellow 

## Steps to Reproduce

N/A

## Expected result

N/A

## Current result

N/A

## Possible Fix

cf map-route Blue sandbox.example.com --hostname demo-time **--shadow 100%**

cf map-route Yellow sandbox.example.com --hostname demo-time **--shadow 7%**

cf map-route Yellow sandbox.example.com --hostname demo-time **--shadow 0%**

## Additional Context

https://www.haproxy.com/blog/haproxy-2-0-and-beyond/

Traffic shadowing, or mirroring, allows you to mirror requests from one environment to another. This is helpful in instances where you would like to send a percentage of production traffic to a testing or staging environment to vet a release before it’s fully deployed.

**Comment by ameowlia** [comment]
Hi @pauldavidgilligan , 

This has been something that has come up over the years, but has never made it in. It is not currently prioritized on our roadmap, but I will bring it up with my leadership.

Given that this would be a large change that would affect many components (at minimum: cf CLI, cloud controller, gorouter) I suggest writing up an identical issue in the [cf-deployment repo](https://github.com/cloudfoundry/cf-deployment) and then link to this issue there. That is a good place to add issues that are for cloud foundry as a whole (even if none of the work actually needs to happen in that repo. Managing distributed systems is hard!)

In the meantime, a possible workaround is to use scaling to your advantage. 

**For example:** 
1. Push 9 v1-apps and map them to blue.my-domain.com
2. 100% of the traffic goes to a v1-app.
3. Push one v2-app and map it to blue.my-domain.com
4. Now 90% of the traffic goes to a v1-app and 10% to a v2-app.
5. When it looks like v2-app is working properly, then scale down v1-apps to 5 and scale up v2-apps to 5. 
6. Now 50% of the traffic to going to v1-app and 50% to a v2-app.
7. When confident, remove v1-app entirely, and 100% of traffic will go to v2.

**Comment by pauldavidgilligan** [comment]
Wonderful thank you for the input @ameowlia I will add this to my HLD for deployment and we will update the other project. Initially we do not not have a large scale value to get such a ratio but I will discuss with the team.

**Comment by ameowlia** [comment]
Given that there is a work around I am going to close this issue. Please re-open in the [cf-deployment repo ](https://github.com/cloudfoundry/cf-deployment) if the workaround stops meeting your needs.

Thanks, 
Amelia Downs, CF Networking Team Member
