### ISSUE TITLE
Streaming files from Cloud Foundry fails at 15 minutes

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/routing-release#194]
## Is this a security vulnerability?
No

## Issue
Long running streaming requests seem to consistently fail at 15 minutes in our Cloud Foundry environments.

## Affected Versions
cf-deployment versions v13.23.0 and v15.5.0 were tested.

## Context
In our environments, long lasting streams end after 15 minutes of successful transfer with no gorouter log. This is related to the slack conversation at https://cloudfoundry.slack.com/archives/C01ABMVNE9E/p1611061285008700

* We've created a test streaming app to parameterize streaming (details in the "reproduce" section).
* We've change settings for `router.frontend_idle_timeout` and `request_timeout_in_seconds` up to 1000 seconds to try to move the failure out. Neither of these settings, nor in combination seem to change the timing of the failure.
* We've tried both dockerized and buildpack apps, as well as a streaming app written in python to see if it was some timeout in a framework. All iterations fail after exactly 15 minutes.
* We've setup a routing service to send requests to a service hosted outside Cloud Foundry. This also fails at 15 minutes, so I would be inclined to rule out envoy and the app container.

## Traffic Diagram 
I am not entirely clear on where the failure occurs, but here is how traffic flows into our system:

AWS classic ELB -> gorouter -> envoy -> application

AWS ELB has an idle timeout of 180 seconds, which doesn't line up with the failure.

## Steps to Reproduce
Find a test streaming application at https://github.com/loafoe/test-stream (can be deployed with a simple manifest.yml).
Once the application is deployed, you can use curl or wget to start a stream. To create a 20 minute stream with 1GB of data, use
```
curl -i https://APPLICATION_ENDPOINT/download/1200/1000 -o foo.bar
```

## Expected result
Since the connection is never idle for more than a few seconds, I expect to be able to retrieve the whole stream after 20 minutes.

## Current result
The stream ends after 15 minutes with an error that looks like this under curl:
```
Jorgensen ~/philips/test-stream $ curl -i https://test-stream-responsive-okapi-oz.cloud.phsdp.com:4443/download/1200/1000 -o foo.bar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  750M    0  750M    0     0   852k      0 --:--:--  0:15:00 --:--:--  932k
curl: (18) transfer closed with outstanding read data remaining
```

## Possible Fix
Perhaps there is a setting that I'm missing which defaults to 15 minutes. I didn't see anything in the spec file for gorouter.

**Comment by pusherofbrooms** [comment]
It turns out that in my tests, I used `router.request_timeout_in_seconds` which seems to be incorrect according to the template. I tested with `request_timeout_in_seconds: 1000` and that moved the failure out to 16m40s as expected.

I've two comments on this.

First, should this setting be under `router.request_timeout_in_seconds` with other timeouts?
Second, the description in the spec file is a bit difficult for me to understand:
```
    description: |
      This configures a "request timeout" and a "backend idle timeout".
      Requests from router to backend endpoints that are longer than this duration will be canceled and logged as
      `backend-request-timeout` errors. In addition, TCP connections between router and backend endpoints that
      are idle for longer than this duration will be closed. Related properties: `router.max_idle_connections`
      and `router.keep_alive_probe_interval`.
```
This hints that it's related to idle connections, but it seems to be a global timeout for active and inactive connections. I don't have any suggestions on better  wording at this time.

**Comment by kkburr** [comment]
Thanks for the feedback. If you come up with a suggestion, feel free to make a PR!
