### ISSUE TITLE
TAS docs state non existing routing release 0.211.1

### ISSUE THREAD

**Issue by mmayr-at** [cloudfoundry/routing-release#197]
## Is this a security vulnerability?
No

## Issue
The TAS docs for [2.10.11](https://docs.pivotal.io/application-service/2-10/overview/release-notes/runtime-rn.html), [2.9.19](https://docs.pivotal.io/application-service/2-9/overview/release-notes/runtime-rn.html) and [2.8.25](https://docs.pivotal.io/application-service/2-8/overview/release-notes/runtime-rn.html) state that routing-release **0.211.0** is included. The latest version here in the repository is **0.211.1**, so either the docs are wrong or the release is missing

## Affected Versions
TAS 2.10.11, 2.9.19, 2.8.25
routing-release 0.211.0 or 0.211.1

## Context
I have some automation to automatically determine the used Go versions by the gorouter included in the different TAS versions.

## Expected result

The routing-release specified in the docs should match the GitHub release

## Possible Fix

State correct version in the docs or add missing release here on GitHub

## Additional Context

![image](https://user-images.githubusercontent.com/16279326/108809058-51aa4180-75a8-11eb-86ef-d9a86fedbde2.png)
![image](https://user-images.githubusercontent.com/16279326/108809087-64247b00-75a8-11eb-82ac-03acf2373856.png)

**Comment by ameowlia** [comment]
Hi @mmayr-at, 

Tanzu is a closed source product and this is an open source repo. From my position as a VMware employee who works on Tanzu, I can say that sometimes we release Tanzu with versions that are not available in the open source. For example, [tanzu 2.6.0](https://docs.pivotal.io/pivotalcf/2-6/pcf-release-notes/runtime-rn.html#2.6.0) uses routing release 0.188.1.

Thanks
