### ISSUE TITLE
Intent to support HTTP/2

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/routing-release#200]
Continuing the legacy of https://github.com/cloudfoundry/gorouter/issues/276

As a follow up to issue #195, we have generated this [proposal](https://docs.google.com/document/d/1vcqlwchibRPnGn2pPQideaW8rmGMGoHFtgrS4RmsVl8/edit) to enable http2 in cloud foundry. 

We will be using this issue as our central coordination point and linking any associated PRs. Please let us know if you have requests or concerns.

**Comment by Gerg** [comment]
Spring Boot H2C Issues:
- https://github.com/spring-projects/spring-boot/issues/25855
- https://github.com/spring-projects/spring-boot/issues/25856

**Comment by Gerg** [comment]
Golang issue for h2c upgrade headers: https://github.com/golang/go/issues/45785

**Comment by ctlong** [comment]
`hey` fork + branch that includes TLS: https://github.com/ctlong/hey/tree/feat/tls. For performance testing.

**Comment by Gerg** [comment]
Golang issue for h2c client upgrade support: https://github.com/golang/go/issues/46249

**Comment by mkocher** [comment]
Updated perf test release: https://github.com/cloudfoundry/routing-perf-release/pull/1

**Comment by Gerg** [comment]
We prototyped an implementation for end-to-end HTTP/2. Here are our prototype implementation branches:
- CAPI Release: https://github.com/cloudfoundry/capi-release/tree/http2_route_destinations
  - Cloud Controller: https://github.com/cloudfoundry/cloud_controller_ng/tree/http2_route_destinations_spike
- Diego Release: https://github.com/Gerg/diego-release/tree/http2_route_destinations
  - Executor: https://github.com/Gerg/executor/tree/http2_route_destinations
  - Routing Info: https://github.com/Gerg/routing-info/tree/http2_route_destinations
  - Route Emitter: https://github.com/Gerg/route-emitter/tree/http2_route_destinations
- Routing Release: https://github.com/Gerg/routing-release/tree/http2_route_destinations
  - Gorouter: https://github.com/cloudfoundry/gorouter/tree/http2_route_destinations

**Comment by Gerg** [comment]
# Proposal for End-to-End HTTP/2

## Background

To support workflows like gRPC routes, Cloud Foundry needs to support HTTP/2 for all network hops between users' applications and their clients. We have not found a satisfactory way to automatically support end-to-end HTTP/2 without breaking HTTP/1 applications. Instead, users will need to apply route destination configuration to enable end-to-end HTTP/2 support for the appropriate routes & apps.

## User Experience

### Typical Routes

For routes that do not require end-to-end HTTP/2, no additional configuration will be required. Apps' clients will be able to issue HTTP/2 requests to all routes, and the foundation's load balancer and Gorouter will serve HTTP/2 traffic. The Gorouter will then forward this traffic over HTTP/1 to the application. We expect that this should be sufficient for the majority of applications and routes.

### API

Route HTTP/2 ingress will be configured via the [Route's Destination sub-resource](https://v3-apidocs.cloudfoundry.org/version/release-candidate/#the-destination-object). Destinations with HTTP/2 enabled will always receive HTTP/2 traffic, and will not be able to negotiate other protocols. Destinations that do not enable HTTP/2 will continue to receive HTTP/1 traffic as they do today.

**Route Resource:**
```json
{
  "guid": "cbad697f-cac1-48f4-9017-ac08f39dfb31",
  "...": "...",
  "destinations": [
    {
      "guid": "385bf117-17f5-4689-8c5c-08c6cc821fed",
      "app": {
        "guid": "0a6636b5-7fc4-44d8-8752-0db3e40b35a5",
        "process": {
          "type": "web"
        }
      },
      "weight": null,
      "protocol": "http2",
      "port": 8080
    },
    "..."
 ],
  "metadata": "...",
  "relationships": "...",
  "links": "..."
}
```

The `protocol` destination field will be readable and updatable consistent with the other currently implemented destination fields, affecting the following endpoints:
1. `GET /v3/routes/:guid/destinations`
1. `POST /v3/routes/:guid/destinations`
1. `PATCH /v3/routes/:guid/destinations`

## User Experience

Implementing this behavior requires small changes to a number of Cloud Foundry components. From a high level, HTTP/2 support for a route destination on the API is propagated into the LRP definition in Diego, which is in turn emitted to the Gorouter, which then routes traffic to that destination over HTTP/2. 

### CAPI Release

In CAPI release, Cloud Controller is the only component that needs modification. A new `protocol` field is added to the Destination resource on the API, which is then persisted in the `route_mappings` table in the database.  

The Cloud Controller then includes this field in the DesiredLRP `routes` field, when creating the app in Diego.

**DesiredLRP:**
```json
{
  "process_guid": "6f641279-...-8cd5f288827a",
  "...": "...",
  "routes": {
    "cf-router": [
      {
        "hostnames": [
          "my-app.example.com"
        ],
        "port": 8080,
        "route_service_url": null,
        "isolation_segment": null,
        "protocol": "http2"
      }
    ],
    "diego-ssh": {
      "...": "..."
    },
    "internal-router": [],
    "tcp-router": []
  },
  "...": "..."
}
```

### Diego Release

Diego release requires modifying the most components, though the changes are relatively small.

#### Route Emitter

Route emitter reads the new protocol field off of the `DesiredLRP` and then publishes it to NATs.

**NATs Message:**
```json
{
  "host": "10.244.0.138",
  "port": 61000,
  "tls_port": 61002,
  "uris": [
    "my-app.example.com"
  ],
  "protocol":"http2",
  "app": "6f641279-56f2-4a08-9ca7-87895241b713",
  "private_instance_id": "e48c25c0-11c7-4c95-6b22-4cf1",
  "private_instance_index": "0",
  "server_cert_domain_san": "e48c25c0-11c7-4c95-6b22-4cf1",
  "tags": {
    "app_id": "6f641279-56f2-4a08-9ca7-87895241b713",
    "app_name": "my-app",
    "component": "route-emitter",
    "instance_id": "0",
    "organization_id": "56666a54-6c37-4af8-a1a1-5209be91e1e8",
    "organization_name": "my-org",
    "process_id": "6f641279-56f2-4a08-9ca7-87895241b713",
    "process_instance_id": "e48c25c0-11c7-4c95-6b22-4cf1",
    "process_type": "web",
    "source_id": "6f641279-56f2-4a08-9ca7-87895241b713",
    "space_id": "add22870-3ed2-4a72-8c9c-e62cb6a17139",
    "space_name": "my-space"
  }
}
```

#### Routing Info

The required changes to routing info are extremely minor. We need to add `protocol` to the common `CFRoute` struct in order to support the changes to route emitter.

#### Executor

The final change for Diego release is in executor, which is responsible for rendering the app's envoy configuration file. Envoy does not accept HTTP/2 traffic by default, so we need to modify the config so that it does.

Envoy will be configured to advertise `h2` and `http/1.1` support for all applications. Gorouter would then be responsible for selecting the appropriate protocol based on the destination's configuration. 

### Routing Release

In routing release, Gorouter is the only component that needs modification. The protocol is read off of the NATs messages and persisted in the Gorouter's routing table for that endpoint.  

**Route Table:**
```json
{
  "...": "...",
  "my-app.example.com": [
    {
      "address": "10.244.0.138:61002",
      "protocol": "http2",
      "tls": true,
      "ttl": 120,
      "tags": {
        "app_id": "6f641279-56f2-4a08-9ca7-87895241b713",
        "app_name": "my-app",
        "component": "route-emitter",
        "instance_id": "0",
        "organization_id": "56666a54-6c37-4af8-a1a1-5209be91e1e8",
        "organization_name": "my-org",
        "process_id": "6f641279-56f2-4a08-9ca7-87895241b713",
        "process_instance_id": "e48c25c0-11c7-4c95-6b22-4cf1",
        "process_type": "web",
        "source_id": "6f641279-56f2-4a08-9ca7-87895241b713",
        "space_id": "add22870-3ed2-4a72-8c9c-e62cb6a17139",
        "space_name": "my-space"
      },
      "private_instance_id": "e48c25c0-11c7-4c95-6b22-4cf1",
      "server_cert_domain_san": "e48c25c0-11c7-4c95-6b22-4cf1"
    }
  ],
  "...": "..."
}
```

When routing traffic to that endpoint, the Gorouter will  negotiate for `h2` over ALPN, as described in the Executor implementation above. For endpoints without this configuration, the Gorouter will continue to send HTTP/1 traffic as it does today.

**Comment by Gerg** [comment]
### Relevant PRs for End-to-End HTTP/2:

- Diego Release:
  - Route Emitter: cloudfoundry/route-emitter#16
  - Routing Info: cloudfoundry/routing-info#2
  - Executor: cloudfoundry/executor#54
- Routing Release:
  - Gorouter: cloudfoundry/gorouter#289
- Capi Release: 
  - Cloud Controller:  cloudfoundry/cloud_controller_ng#2439
- CF Acceptance Tests: cloudfoundry/cf-acceptance-tests#473

**Comment by plowin** [comment]
Hi @Gerg , is there a reason why this is still open?

**Comment by Gerg** [comment]
Not that I'm aware of. I'll go ahead and close it.
