### ISSUE TITLE
Gorouter overwrites any existing X-VCAP-Request-ID header

### ISSUE THREAD

**Issue by andy-paine** [cloudfoundry/routing-release#207]
## Issue
The gorouter overwrites any existing X-VCAP-Request-ID

## Affected Versions
Every version after 2014

## Context
Sometimes users experience timeouts etc., particularly when talking to the Cloud Controller. As they do not get a response back, they cannot correlate their request to any logs in the Cloud Controller/gorouter for debugging purposes. The Cloud Controller has [some code to handle incoming VCAP request IDs](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/middleware/vcap_request_id.rb) which appends a random GUID to ensure uniqueness (in case a user provides the same request ID for multiple requests). However, as the gorouter [adds in its own VCAP request ID](https://github.com/cloudfoundry/gorouter/blob/main/handlers/request_id.go), a user cannot provide one that will be logged by the gorouter.

## Steps to Reproduce
* Query a CF API (e.g. `/v3/info`) through the gorouter with a `X-VCAP-Request-ID: foobarbaz` header set

## Expected result
Response should contain a header including original e.g. `X-VCAP-Request-ID: foobarbaz::9599215f-b46e-4ec0-93a9-2bf859379c5c`

## Current result
Response contains completely random pair of GUIDs e.g. `X-VCAP-Request-ID: c4b276ed-2861-4f4d-6957-c5b2a08d72b8::9599215f-b46e-4ec0-93a9-2bf859379c5c`

## Directly via Cloud Controller
To demonstrate that it is the gorouter behaviour, you can `bosh -d cf ssh api/0` and query the API directly (`localhost: 9022/v3/info`) with the header, you can see the original header appears in the response header with a random GUID appended

## Possible Fix
Only set an `X-VCAP-Request-ID` if one isn't already set. This is the behaviour of the [zipkin headers](https://github.com/cloudfoundry/gorouter/blob/main/handlers/zipkin.go) since those need forwarding between requests so the code change shouldn't be complicated. 

## Additional Context
When the request ID generation was added to the gorouter it was explicitly made so that existing headers would be overwritten (see [comment](https://github.com/cloudfoundry/gorouter/pull/29#issuecomment-38472016)). I don't know if this still holds true - the gorouter still uses this generated ID for logging as it serves as the unique identifier but clearly at [some point far in the past](https://github.com/cloudfoundry/cloud_controller_ng/commit/646ebb75ca3e89574fbcd293f05cdbd663d5afb7#diff-7d0ce2b33f3621249bc76ceff9cceeecc6f475b54e6477132114803c772abf19) this was a feature the Cloud Controller supported which I suspect has been broken since CC started being deployed behind the gorouter.

I'm not sure on what the impact of this change would be at the gorouter level. To guarantee uniqueness the gorouter may have to append a new GUID (like CC does) but this may affect apps that talk via the gorouter (e.g. route services) as this effectively changes the format of the request ID.

The easiest alternative may be if CC preferred `X-Request-ID` over `X-VCAP-Request-ID` since then users _can_ provide their own if needed and CC already looks after the uniqueness constraint.

I would be interested in your thoughts and potential impact. The user need for "I need to know what happened to this request that never responded" seems valid so it would be good to support that.

**Comment by Gerg** [comment]
I'd like to understand more about 
> Sometimes users experience timeouts etc., particularly when talking to the Cloud Controller. As they do not get a response back, they cannot correlate their request to any logs in the Cloud Controller/gorouter for debugging purposes.

What is timing out in this case? Cloud Controller? Gorouter? Something in front of Gorouter?

Without understanding more about this issue, it sounds like an alternative solution would be to ensure that Gorouter returns the X-VCAP-Request-ID header when a request times out.

**Comment by andy-paine** [comment]
In this situation it is the client that is calling the Cloud Controller is what is timing out or to be more correct, is closing the connection after a certain period. When users ask what happened to a long-running request that the client timed out they don't know the VCAP request ID so we can't find the correct logs to see what CC was doing. Some of these users have offered to include a header as a way of identifying each request that would be included in all logs so the suggestion was to allow a user-supplied request ID.

Always returning the request ID in the response doesn't really work in this scenario I think since it is the client that is closing the connection so they would never receive the response. Obviously these timeouts could be increased but it seems reasonable that a request should either succeed or error within 30/60/300 seconds without just having to wait for the gorouter's 15 minute timeout to return a 5xx response with a request ID header.

**Comment by stephanme** [comment]
In addition the [multiapps](https://github.com/cloudfoundry-incubator/multiapps) team had the use case to correlate CF API logs with data in other application performance monitoring tools. This is easier to achieve if the user has control over correlation ids.

Maybe @boyan-velinov can provide more insights.

**Comment by Gerg** [comment]
This idea sounds appealing:
> The easiest alternative may be if CC preferred X-Request-ID over X-VCAP-Request-ID since then users can provide their own if needed and CC already looks after the uniqueness constraint.

I dug into the history some, but I couldn't find any clues on why the `X_REQUEST_ID` header exists or is overridden by `X_VCAP_REQUEST_ID`: https://github.com/cloudfoundry/cloud_controller_ng/commit/646ebb75ca3e89574fbcd293f05cdbd663d5afb7

If you agree this is a good path forward, you can transfer this issue to Cloud Controller: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by Gerg** [comment]
Checking back on this issue @andy-paine @stephanme. What do you think about transferring this to Cloud Controller?

**Comment by stephanme** [comment]
I understand that the gorouter wants to be in control of the vcap-request-id so that there is a guaranteed unique correlation id for tracing within CF that a user can't tamper with.

On the other side I see the end user need to understand if a client request reached the platform. To find out if a client request reached the CC, the proposed "easiest alternative" (prefer X-Request-ID over X-VCAP-Request-ID in CC) would work.
 
An even better and probably simpler solution in my eyes would be if the gorouter would just log a provided X-Request-ID together with the generated X-VCAP-Request-ID (and X-VCAP-Request-ID is used consistently in the platform).
This would:
- allow a user to check if a client request reached CF (the routing tier)
- allow to correlate a client request with the request processing in CF (via one indirection logged by gorouter)
- keep the existing semantics of X-VCAP-Request-ID
- be a minimal change to the gorouter and CC (maybe even no change is needed, see below)

Disadvantages I could think of: 
- increases size of gorouter request logging
- tracing requires one indirection (mapping of X-Request-ID to X-VCAP-Request-ID)
- if there are components like haproxy processing a request before gorouter, X-Request-ID should be logged additionally (in case of problems between haproxy and gorouter)

Maybe this is already possible using https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry/routing-release&version=0.228.0#p%3drouter.extra_headers_to_log

**Comment by mariash** [comment]
This behavior of `X-VCAP-Request-ID` was around for almost a decade and changing it might be breaking change for some users who expect current behavior.  @andy-paine if you want the tracing header provided by user be honored by the Gorouter and propagated to every other component down stream can you use zipkin or W3C headers for this?

**Comment by dsabeti** [comment]
Closing this issue as @mariash has provided a workaround. Feel free to re-open if there's additional discussion to be had.
