### ISSUE TITLE
gorouter.yml template rendering errors

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/routing-release#225]
The bosh team recently shipped a version of the bosh director that uses ruby 3. We got a report that this has broken the rendering of the `gorouter.yml` template.

https://github.com/cloudfoundry/bosh/issues/2322

We've tracked the issue down to a bump in the version of libyaml we package with the ruby release. We're trying to find a workaround but wanted to bring this to your attention so the template can be "fixed" while we work on a temporary fix from our side.

Newer versions of libyaml treat multiple new lines at the end of a document as needing a document break `...`, since gorouter.yml is doing multiple `to_yaml` renderings in a single file, when those intermediary yaml documents are rendered, if they have multiple new lines at the end, you end up with `...` output too, and since gorouter.yml is combining all of these document fragments together, you end up with `...` in the middle of a file.

We'd suggest you just build up a hash structure in the erb then run `to_yaml` a single time at the end.

**Comment by geofffranks** [comment]
@jpalermo This should be resolved with https://github.com/cloudfoundry/routing-release/commit/eb9051671d094af2dc1ff699a4de95865b4dbb91. Should be in the next routing release (hopefully this week)
