### ISSUE TITLE
Route-service not logging target URL in case of errors

### ISSUE THREAD

**Issue by plowin** [cloudfoundry/routing-release#242]
## Issue

Route service logs could be enhanced with more metadata. Proposol for an enhancement on the gorouter repo: https://github.com/cloudfoundry/gorouter/pull/301
If filling out this template is still required, please ping me

## Traffic Diagram 

 
```
EXAMPLE DIAGRAM - please draw your own at asciiflow.com
           +----+---+    +----------+     +-------+
  \o/      |        |    |          |     |       |
   +  +--->+ AWS LB +--->+ Gorouter +---->+  App  |
  / \      |        |    |          |     |       |
 client    +--------+    +----------+     +-------+
```

**Comment by ameowlia** [comment]
Merged!

**Comment by plowin** [comment]
Thanks a lot!
Just for next time: Is an issue required to have the PR on some board or is only the PR sufficient if it is small enough?

**Comment by ameowlia** [comment]
Only a PR is needed for small changes that affect only one job.
