### ISSUE TITLE
Improve handling of x-cf-forwarded-uri when requests use absolute URI (possible with http 1.1) instead of relative path

### ISSUE THREAD

**Issue by jmotex** [cloudfoundry/routing-release#248]
## Is this a security vulnerability?
No

## Issue
CF route services have the x-cf-forwarded-url header set by the router.
For typical requests that send only relative path as the request-URI things work fine, but when an absolute-URI is sent it causes a malformed x-cf-forwarded-url header.  It appears x-cf-forwarded-url is just host+URI so host+absoluteURI = hosthttp://host/path as an example of a malformed url format.  This causes the route service to not be able to make the request to onto the target backend service.

As per https://datatracker.ietf.org/doc/html/rfc2616#section-5.1.2, "To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies."

So this appears to be a HTTP 1.1 related error on the CF server side.  Due to a concatenation of host and URI.

The request was accepted but internal processing is broken.

## Affected Versions
Seen in CF deployment 16.22 with routing 0.221.0

## Context
Debug logs show a malformed x-cf-forwarded-url header received in proxy configured via CF route services when sender uses absolute URIs.   e.g. GET http://abc.com/def and HOST: abc.com results in x-cf-forwarded-url: abc.comhttp//abc.com/def

## Steps to Reproduce

Create a CF route service and bind to a target app.  Send a HTTP GET request with absolute URI e.g. GET http://abc.com/def and host header.  Check the x-cf-forwarded-url received at the route service.

## Expected result

x-cf-forwarded-url should be of the form http://abc.com/def, not malformed.

## Current result

Malformed x-cf-forwarded-url header

## Possible Fix

Check the type of URI and adjust how the x-cf-forwarded-url is constructed.

File: https://github.com/cloudfoundry/gorouter/blob/main/handlers/routeservice.go
Line 118: 	forwardedURLRaw := recommendedScheme + "://" + hostWithoutPort(req.Host) + req.RequestURI

This could be changed to check if the req.RequestURI is relative path or absolute URI.  If absolute then set forwardedURLRaw = req.RequestURI

**Comment by geofffranks** [comment]
This appears to have been fixed at some point. When replicating, I was unable to get a malformed x-cf-forwarded-url:

```
GET http://testapp.neat-299560.cf-app.com/dumprequest/ HTTP/1.1
GET http://testapp.neat-299560.cf-app.com/dumprequest/ HTTP/1.0
GET /dumprequest/ HTTP/1.1
```

all resulted in `X-Cf-Forwarded-Url: https://testapp.neat-299560.cf-app.com/dumprequest/`
