### ISSUE TITLE
Invalid X-B3-SpanId header values (too long)

### ISSUE THREAD

**Issue by datagitlies** [cloudfoundry/routing-release#264]
## Is this a security vulnerability?
No

## Issue
**gorouter**: The Zipkin TraceID changed to 16 bytes in commit [e5d7aab](https://github.com/cloudfoundry/gorouter/commit/e5d7aab0b68ed16f3ea36caa2a739e68dc5c2779#diff-fc39773fc82299500e2f352a061aa51e1fbcdf601da478b627e99caf2c423ebaR48) which is / was a "valid" change.  However, since the TraceID and SpandID values are the same, this gives the SpanID an invalid length.  Reference here -> https://github.com/openzipkin/b3-propagation#identifiers

>**TraceId**
>The TraceId is 64 or 128-bit in length and indicates the overall ID of the trace. Every span in a trace shares this ID.
>
>**SpanId**
>The SpanId is 64-bit in length and indicates the position of the current operation in the trace tree. The value should not be interpreted: it may or may not be derived from the value of the TraceId.

## Affected Versions

Unknown

## Context

When using `spring-cloud-sleuth` the gorouter provides invalid `X-B3-SpanId` headers (too long) and this causes problems with traceability as certain frameworks cannot properly interpret the header value because they are looking for 8 bytes (64-bit).

## Traffic Diagram 

N/A

## Steps to Reproduce

1. Send a request to the gorouter without providing `b3` / `X-B3-TraceId` / `X-B3-SpanId` headers and let the gorouter generate these headers automatically.  
2. Observe that the trace and span header values are identical and both are 16 Bytes (128-bit) in length.

## Expected result

The `X-B3-SpanId` header (and by virtue the `b3` header) should only contain a SpanID that is 8 Bytes (64-bit) in length.

## Current result

The `X-B3-SpanId` header (and by virtue the `b3` header) contains a SpanID that is 16 Bytes (128-bit) in length - which is too long.

## Possible Fix

Update the [handlers/zipkin.go](https://github.com/cloudfoundry/gorouter/blob/main/handlers/zipkin.go) to produce the correct length header values.

## Additional Context

none

**Comment by plowin** [comment]
Hi @datagitlies , with which release were you observing this? We also saw this issue but I thought it was fixed with [0.229.0](https://github.com/cloudfoundry/routing-release/releases/tag/0.229.0) and was introduced with 0.227.0?

**Comment by mariash** [comment]
@datagitlies the implementation has changed since this bug was introduced and [now span id is correctly set](https://github.com/cloudfoundry/gorouter/blob/e9019bfbef3d9d68c9a941745eb073173aa2fcca/handlers/requestinfo.go#L141) Let us know if latest release works for you.
