### ISSUE TITLE
gorouter error message for route-service timeout is misleading

### ISSUE THREAD

**Issue by maxmoehl** [cloudfoundry/routing-release#272]
## Issue

Gorouter does not properly throw errors when a route-service timeout is hit.

## Affected Versions

Tested with:
```
cf-deployment: v17.1.0
routing-release: 0.226.0
```
but it seems like the issue is still present in more recent versions.

## Context

We deployed a route-service that violates the configured 60s route-service timeout. We expected to receive a response that indicates a route-service failure. Instead we received a error message that validating the `x-forwarded-client-cert` failed:

```
> GET / HTTP/1.1
> Host: app.cf.example.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-length: 88
< content-type: text/plain; charset=utf-8
< date: Fri, 20 May 2022 12:09:53 GMT
< set-cookie: JSESSIONID=b3dd2581-8e96-44cc-933f-6595b1137cba
< set-cookie: __VCAP_ID__=80b3a715-d8e2-4f85-5036-2371
< x-content-type-options: nosniff
< x-vcap-request-id: 480d6550-16bd-4d5d-55b6-8561579f0487
< strict-transport-security: max-age=31536000; includeSubDomains; preload;
<
400 Bad Request: Failed to validate Route Service Signature for x-forwarded-client-cert
```

Looking at the code it seems like [1] configured a validation that is intended to handle client certificate related headers. However, it also validates the route service parts [2]. The main issue is that the original error gets swallowed at [3] and only written to the error log, instead of also sending it back to the client to indicate what the underlying issue was. The hardcoded error message that includes the `x-forwarded-client-cert` header adds to the confusion because this header has nothing to do with the error as far as we can tell.

[1] https://github.com/cloudfoundry/gorouter/blob/be23445bf155a4c4f8cfbc764eab6ff80f0c24bc/proxy/proxy.go#L190-L190
[2] https://github.com/cloudfoundry/gorouter/blob/be23445bf155a4c4f8cfbc764eab6ff80f0c24bc/proxy/proxy.go#L227-L227
[3] https://github.com/cloudfoundry/gorouter/blob/be23445bf155a4c4f8cfbc764eab6ff80f0c24bc/handlers/clientcert.go#L57-L67

## Traffic Diagram 

```
┌──────────┐    ┌───────────────┐    ┌──────────┐
│          │    │               │    │          │
│ gorouter ├───►│ route service ├───►│ gorouter │
│          │    │               │    │          │
└──────────┘    └───────────────┘    └──────────┘

   ├───────────────────60s───────────────────┤
                     timeout
```

## Steps to Reproduce

1. Deploy a user-provided route-service that waits at least 60s before forwarding the request
2. Bind it to any route
3. Execute a request towards that route

## Expected result

An error message that explains what went wrong, e.g. `502 Bad Gateway: Route Service Timeout` or something similar.

## Current result

`400 Bad Request: Failed to validate Route Service Signature for x-forwarded-client-cert`

## Possible Fix

It seems like the validation for the client cert is happening before the route-service validation which causes this issue. Maybe changing the order of the validation could help.

**Comment by domdom82** [comment]
Maybe a `504 Gateway Timeout` would be even more appropriate than a `502 Bad Gateway`.

**Comment by geofffranks** [comment]
👋 taking a look at the PR now!
