### ISSUE TITLE
Log all headers to comply with M-21-31

### ISSUE THREAD

**Issue by dandersonsw** [cloudfoundry/routing-release#286]
## Is this a security vulnerability?
No

## Issue
Currently, non-standard headers are not logged unless specified using the `extra_headers_to_log` field, which requires a list of known headers to log.

## Affected Versions
Unknown

## Context

In order to comply with [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf) we would like to be able to log all headers that get sent on a request.

## Traffic Diagram 

N/A

## Steps to Reproduce

Make a curl request and pass a non-standard header with it. Check the logs to see that the header does not show.

## Expected result

I would expect to see any header that was passed with a request in the logs.

## Current result

Non-standard headers are not shown in the logs.

## Possible Fix

Allow use of a wildcard option for `extra_headers_to_log`, or add another option that can be set to allow logging of all headers.

## Additional Context

N/A

**Comment by MarcPaquette** [comment]
@mkocher,

I wanted to run this by you and your team before we brought this in for consideration. Any thoughts or guidance?

Thanks!

**Comment by mkocher** [comment]
Logging all the headers is likely to be an unacceptable security risk to a lot of CF operators, as the headers would capture session authentication info for CF as well as all the apps on the platform. We could add a deny list in routing-release for headers to not log, but that deny list would be platform level while each app could have any number of sensitive headers.

Headers might also generate a bunch more log data, gorouter by default caps headers at 1MB I think.

So I wouldn't want to see this made the default behavior. I wouldn't object to making it optional, but it doesn't seem like something I'd encourage anyone to use.

**Comment by mariash** [comment]
@dandersonsw is this still relevant? Since this has been open for more than a year?
