### ISSUE TITLE
Gorouter error handling regression on golang 1.20

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/routing-release#311]
## Issue

After upgrading to golang 1.20, gorouter's [error handler](https://github.com/cloudfoundry/gorouter/blob/main/proxy/round_tripper/error_handler.go#L47-L58) broke. Requests that previously would return 496, 499, 503, 525, and 526 codes may now return 502s. Stale routes that were previously pruned are now not pruned.

## Affected Versions

0.258.0, 0.259.0, 0.260.0

## Context

Golang release note regarding the issue:
https://go.dev/doc/go1.20#minor_library_changes (see the crypto/tls + crypto/x509 sections)
[Gorouter failure classifier code where we should fix](https://github.com/cloudfoundry/gorouter/tree/main/proxy/fails)
[A potential way to future proof how we classify errors:](https://pkg.go.dev/errors#Is) errors.As() or errors.Is()

**Impact**
- Operators will have a harder time diagnosing whether 502s returned by an app are from app failure/networking issues, or from platform issues related to cert management or stale routing
- Route pruning will not occur properly anymore, which could lead to unnecessary 502s for apps with stale routes.

## Possible Fix

Modify the error classifiers to use errors.As() and errors.Is() instead of using explicit type checking.

**Comment by domdom82** [comment]
@geofffranks this should be fixed in the linked PR. Can you verify + close?

**Comment by geofffranks** [comment]
Verified as fixed.
