### ISSUE TITLE
Bump HAProxy to fix a bug with reloading + reused sockets

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/routing-release#317]
HAProxy [had a bug](https://github.com/haproxy/haproxy/issues/1883) that we encountered where reloading the process + reusing existing sockets sometimes failed to succeed.

This has been fixed as of HAProxy v2.7.6 (and 2.5.13). We should update routing-release to include a fixed version of haproxy for cf-tcp-router.

**Comment by geofffranks** [comment]
v2.7.4+ and v2.5.13+ of haproxy also include a commit ("Don't rearm the read expiration date if") which causes periodic crashes, hangs, and CPU issues. We should wait until [haproxy/#2111](https://github.com/haproxy/haproxy/issues/2111) is fixed before bumping here.

I'm going to revert the bump from 0.263.0 and publish 0.264.0 shortly.

**Comment by ameowlia** [comment]
Any update on this @geofffranks ?

**Comment by geofffranks** [comment]
We bumped to 2.7.8, and this can be closed. Thanks for the bump, I lost track of this.
