### ISSUE TITLE
Gorouter spends almost 8% of CPU time comparing Endpoints

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/routing-release#366]
## Is this a security vulnerability?
No

## Issue
In one of our largest CF deployments we have seen CPU spikes on gorouter during high NATS load.
The NATS load occurs because lots of app routes get refreshed which causes logs of messages to be sent to all gorouters.

While digging into the issue we also ran several [pprof](https://github.com/google/pprof) profiles which have surfaced a bottleneck in the `RouteRegistry.Register` area.

When gorouter checks whether it should insert a new endpoint in the endpoint pool or update an existing one, it checks if the new endpoint [equals the existing one](https://github.com/cloudfoundry/gorouter/blob/main/route/pool.go#L254C3-L254C3) in the pool.

As it turned out, the [equality check](https://github.com/cloudfoundry/gorouter/blob/main/route/pool.go#L104) uses an expensive call to `fmt.Sprint` on the `tags` field of either endpoint. The call is expensive because it stringifies both maps into a sorted string and then compares the strings.

## Affected Versions
All

## Context

[pprof.gorouter.samples.cpu.002.pb.gz](https://github.com/cloudfoundry/routing-release/files/13515314/pprof.gorouter.samples.cpu.002.pb.gz) contains the pprof that we pulled from gorouter during heavy load.

Here is an overview flame graph that shows a significant time being spent in `mbus.Subscriber` which is the NATS client receiving `router.register` messages.

<img width="1596" alt="gorouter-pprof-total" src="https://github.com/cloudfoundry/routing-release/assets/1755853/a79be59b-8959-4b11-aa14-d75498494d6a">

When zooming into the subscriber, we see that it is actually `Endpoint.Equal` and by extension `fmt.Sprint` that takes the largest chunk of time. The whole `registry.Register` call is about 8% of the sample CPU time with `Endpoint.Equal` being about 6% totally.

<img width="1585" alt="gorouter-pprof-register" src="https://github.com/cloudfoundry/routing-release/assets/1755853/57a3106b-0a0d-4f02-95bd-9c6f7cd2c1e8">

## Steps to Reproduce

1. Enable [debug_address](https://github.com/cloudfoundry/routing-release/blob/develop/jobs/gorouter/spec#L91) in routing-release
2. Deploy routing-release
3. Deploy lots of apps and routes (30k+)
4. Put lots of traffic on gorouter (10k+)
5. Watch CPU load
6. `go tool pprof https://<gorouter debug endpoint>`

## Expected result

Gorouter should spend most of its time serving HTTP traffic.

## Current result

Gorouter spends almost 10% of its time comparing endpoints.

## Possible Fix

We did some digging and thanks to @peanball we found a great alternative to the expensive `fmt.Sprint` call.
Since go 1.21 there is a great [maps package](https://pkg.go.dev/maps@master#Equal) that provides an `Equal` function to compare maps.

Preliminary tests using the [registry_benchmark_test](https://github.com/cloudfoundry/gorouter/blob/main/registry/registry_benchmark_test.go) have shown an improvement of about 20x in time spent on inserting nodes. (BenchmarkEndpointEquals-16 going from 1597 ns/op to 83.46 ns/op)

If our assumptions are correct, this means we could cut the time spent on endpoints from 8% to roughly 0.5% of CPU time.

We will do additional tests and provide a PR that fixes the performance issue.

**Comment by maxmoehl** [comment]
The fix was merged into routing-release with 498424191cd898ff636d0d4e461fbcae64feee57.
