### ISSUE TITLE
Gorouter no longer prefers specific SNI matches over wildcard SNI matches

### ISSUE THREAD

**Issue by maxmoehl** [cloudfoundry/routing-release#401]
## Is this a security vulnerability?

No.

## Issue

Gorouter will pick the first certificate that matches the SNI and not look for a certificate that might match SNI completely.

## Affected Versions

0.293.0 and newer

## Context

When providing multiple certificates to gorouter, they will be loaded in the order they are specified. Prior to cloudfoundry/gorouter@6c6bd520ad939910fe8c0830558f6dd179e7d113 we would build the [NameToCertificate](https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/crypto/tls/common.go;l=1141) list which prefers full matches over wildcard matches on the SNI. Now that this list is no longer set the library picks the first certificate that matches, even if there is a certificate in the list which matches the entire SNI instead of just the wildcard.

## Traffic Diagram 

N/A

## Steps to Reproduce

1. Configure two certs, the first one with `*.cf.local` and the second with `test.cf.local`
2. Make a request with the SNI `test.cf.local`

## Expected result

The second certificate is presented as it is the more specific fit.

## Current result

The first certificate is presented because it already matches the SNI provided by the client.

## Possible Fix

Revert the commit.

Alternative tbd.

**Comment by maxmoehl** [comment]
@geofffranks I will go ahead and put a breaking change marker into the release so that others are aware. I'm also preparing a revert as we are now stuck on 0.292.0 and I'm assuming that this was an unintended consequence from an innocent refactor?

**Comment by geofffranks** [comment]
If this is a relied upon behavior, we should add tests to catch this in the future. I'll pull in the revert and add a linter ignore to get a new version out today.
