### ISSUE TITLE
Implement per-route options in gorouter

### ISSUE THREAD

**Issue by maxmoehl** [cloudfoundry/routing-release#421]
### Proposed Change

As a user,
I want to control how the routing stack talks to my app,
so that I can better align the traffic to the needs of my application.

In [RFC0027 Generic Per-Route Features](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0027-generic-per-route-features.md) we decided to implement a new field for nats messages which can contain additional, custom configuration for a route. Together with this new feature we also want to implement the first property making use of it: customisable load balancing algorithms.

### Acceptance criteria

* [ ] gorouter is able to parse the new field containing the per-route options
* [ ] gorouter adjusts the load balancing algorithm for routes that provide the field

**Comment by Dariquest** [comment]
Corresponding PR https://github.com/cloudfoundry/gorouter/pull/428
