### ISSUE TITLE
Double logging happens when using the syslog-release

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/routing-release#97]
## Issue

Due to the `tee`ing of output to the `logger` command (via the `tee_output_to_sys_log` function), when [syslog-release](https://github.com/cloudfoundry/syslog-release) is used to send all log files to syslog, we get double entries in syslog.

## Possible Fix

Stop `tee`ing output to `logger`?

**Comment by shalako** [comment]
Hi @jpalermo, good to hear from you.

Which log files are you referring to in particular and for what jobs? e.g. `router/gorouter.log`? 

Can I assume that this doesn't require a change to our existing behavior with regard to local logging and streaming via metron agent?

**Comment by jpalermo** [comment]
For out particular use case, it was `/var/vcap/sys/log/route_registrar/route_registrar.log` and `/var/vcap/sys/log/route_registrar/route_registrar.err.log` since we are only co-locating the `route_registrar` job.

However, it seems like this is done in most of the routing control scripts currently.

I don't think it would require any behavior changes to local logging or streaming via metron agent. 

The mysql team just made a similar change, we in fact had the exact same `tee_output_to_sys_log` function that we just changed to `output_to_logfiles` by removing the `tee` and `logger` portions:
https://github.com/cloudfoundry/cf-mysql-release/commit/6f9092f1ad502afbd174b342568b3f975d96d47c#diff-42cc39d7414a1cfa8dacaf8f775ec671

This allowed us to remove any syslog code and properties from our release, and simply rely on the syslog-release to send all log files in `/var/vcap/sys/log` to syslog for us.

**Comment by menicosia** [comment]
Hello @shalako @shubhaat,

Just curious if there's any chance you'll prioritize this issue? It's just a bit odd that we're double-syslogging routings' log messages.

**Comment by shalako** [comment]
To be honest, we're not likely to get to it soon. If you've got the bandwidth to make a PR, it would be welcome as long as it doesn't impact logging behavior otherwise. @aaronshurley

**Comment by aaronshurley** [comment]
Once we switch to using [BPM](https://github.com/cloudfoundry-incubator/bpm-release) ([stories](https://www.pivotaltracker.com/n/projects/1358110/search?q=label%3A%22bpm%22)), this issue should be resolved

**Comment by menicosia** [comment]
👍

**Comment by KauzClay** [comment]
We have completed the adoption stage for BPM. Are you still seeing this issue?

**Comment by adobley** [comment]
@jpalermo @menicosia Given that the BPMification of our jobs should have fixed this and that there are no new updates, I'm going to close this for now. Please re-open or reach out to our team if you have any updates. :)

Thanks!
