### ISSUE TITLE
gorouter closing connection to client before writing the whole response body

### ISSUE THREAD

**Issue by samzilverberg** [cloudfoundry/routing-release#98]
we've traced down a possible unexpected behavior (in our eyes) to gorouter.
@jriguera can provide more details about our cloudfoundry/gorouter env if needed.

the scenario is a client uploading a large file, with the server limiting to a max file size (say 2 mb) by reading up-to 2mb from the upstream.
if this limit is reached, the server immediately responds with 413, connection:close header and some response body (of around 50k size).
this results in closing the conn from the server side, AFTER writing the whole response body (so its available to the client side).

when making these kind of requests to the server directly (via curl or a minimal client impl) we get the whole response on the client side. even if the client is still in the middle of uploading (didnt finish the req).

when doing the same with gorouter in the middle, we either get an err or a partial response body.
the errors vary but are usually either `curl: (55) Send failure: Broken pipe` or `curl: (56) Recv failure: Connection reset by peer`.

I've posted the above ^^ on slack and was prompted by @rosenhouse to open an issue here.
he also mentioned:
>I believe this is known behavior in Gorouter (and other HTTP reverse proxies, for that matter https://github.com/envoyproxy/envoy/issues/2067 )

**Comment by samzilverberg** [comment]
debugging we've found the problem in gorouter code, in:

https://github.com/cloudfoundry/gorouter/blob/master/proxy/round_tripper/proxy_round_tripper.go#L100-L106

these changes were introduced as a fix for https://github.com/cloudfoundry/gorouter/issues/130
in commit: https://github.com/cloudfoundry/gorouter/commit/055fee9a69e8dc5fc9acb94e5790ee17df5dd365

when commenting out the `if request.Body != nil {...}` clause our issue doesn't appear.
were not confident enough introducing a PR that would fix our issue while still solving the other one, perhaps the original commiters are still around and can take a look?

**Comment by rosenhouse** [comment]
Closing in favor of https://github.com/cloudfoundry/gorouter/issues/212

**Comment by thausler786** [comment]
@rosenhouse I notice that you closed this issue in favor of cloudfoundry/gorouter#212.  However, you also closed that issue in favor of this one.  This was probably a mistake?

**Comment by rosenhouse** [comment]
@thausler786 https://github.com/cloudfoundry/gorouter/issues/212 is still open.  you might be getting thrown off by the red box at the bottom of that page... which is an indicator of this issue 😄
